prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/user_interfaces.sql
@@application/shared_components/pwa/screenshots/sb_export_portal.sql
@@application/shared_components/navigation/lists/access_control.sql
@@application/shared_components/navigation/lists/questions_for_output.sql
@@application/shared_components/navigation/lists/data_load_proforma.sql
@@application/shared_components/navigation/lists/custom_invoice_steps.sql
@@application/shared_components/navigation/lists/data_load_manufacturers.sql
@@application/shared_components/navigation/lists/data_load_products.sql
@@application/shared_components/navigation/lists/user_settings.sql
@@application/shared_components/navigation/lists/desktop_navigation_menu.sql
@@application/shared_components/navigation/lists/desktop_navigation_bar.sql
@@application/shared_components/navigation/listentry.sql
@@application/shared_components/files/app_setup_config_js.sql
@@application/shared_components/files/app_setup_config_min_js.sql
@@application/shared_components/files/costing_min_js.sql
@@application/shared_components/files/costing_js.sql
@@application/shared_components/files/januzlogo_png.sql
@@application/shared_components/files/januz_universal_online_help_pdf.sql
@@application/shared_components/files/sep_online_help_pdf.sql
@@application/shared_components/files/logosblogin_png.sql
@@application/shared_components/files/icons_app_icon_512_png.sql
@@application/shared_components/files/icons_app_icon_256_rounded_png.sql
@@application/shared_components/files/icons_app_icon_192_png.sql
@@application/shared_components/files/icons_app_icon_144_rounded_png.sql
@@application/shared_components/files/icons_app_icon_32_png.sql
@@application/shared_components/files/pwa_logo_white_bkg_org_jpg.sql
@@application/shared_components/files/loading_gif.sql
@@application/shared_components/files/2020_jpg.sql
@@application/shared_components/files/snowman_gif.sql
@@application/shared_components/files/image0_jpg.sql
@@application/shared_components/files/proforma_upload_template_xlsx.sql
@@application/shared_components/files/spriteblend_png.sql
@@application/shared_components/files/favicon_ico.sql
@@application/shared_components/files/image1_jpg.sql
@@application/shared_components/files/image2_jpg.sql
@@application/shared_components/files/image3_jpg.sql
@@application/shared_components/files/image4_jpg.sql
@@application/shared_components/files/multislider_js.sql
@@application/shared_components/files/jquery_js.sql
@@application/shared_components/files/multislider_min_js.sql
@@application/shared_components/files/excel_pdf_png.sql
@@application/shared_components/files/copy_icon_png.sql
@@application/shared_components/files/pdf_logo_png.sql
@@application/shared_components/files/delete_png.sql
@@application/shared_components/files/export_excel_icon_png.sql
@@application/shared_components/files/product_upload_template_xlsx.sql
@@application/shared_components/files/container_percent_small_png.sql
@@application/shared_components/files/info_png.sql
@@application/shared_components/files/saarthi_whitebg_jpg.sql
@@application/shared_components/files/saarthi_white_png.sql
@@application/shared_components/files/texture_11_png.sql
@@application/shared_components/files/test1_gif.sql
@@application/shared_components/files/testr_gif.sql
@@application/shared_components/files/test_gif.sql
@@application/shared_components/files/reversecubicspacecalc_xlsx.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/sb_administration_rights.sql
@@application/shared_components/security/authorizations/sb_business_user_rights.sql
@@application/shared_components/security/authorizations/sb_manager_rights.sql
@@application/shared_components/security/authorizations/sb_super_user_rights.sql
@@application/shared_components/security/authorizations/sb_warehouse_rights.sql
@@application/shared_components/security/authorizations/sb_readonly_rights.sql
@@application/shared_components/security/authorizations/sb_delete_rights.sql
@@application/shared_components/security/authorizations/sb_finance_rights.sql
@@application/shared_components/security/authorizations/sb_hide_sensitive_info.sql
@@application/shared_components/security/app_access_control/administrator.sql
@@application/shared_components/security/app_access_control/account_user.sql
@@application/shared_components/security/app_access_control/business_user.sql
@@application/shared_components/security/app_access_control/manager.sql
@@application/shared_components/security/app_access_control/super_user.sql
@@application/shared_components/security/app_access_control/warehouse_user.sql
@@application/shared_components/security/app_access_control/delete_access.sql
@@application/shared_components/security/app_access_control/readonly_access.sql
@@application/shared_components/security/app_access_control/finance.sql
@@application/shared_components/security/app_access_control/hide_sensitive_info.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_processes/get_setup_values.sql
@@application/shared_components/logic/application_processes/download_pdf_file.sql
@@application/shared_components/logic/application_items/app_color_enq_aw.sql
@@application/shared_components/logic/application_items/app_color_enq_ip.sql
@@application/shared_components/logic/application_items/app_color_enq_rj.sql
@@application/shared_components/logic/application_items/app_color_ord_ds.sql
@@application/shared_components/logic/application_items/app_color_ord_poi.sql
@@application/shared_components/logic/application_items/app_color_ord_ppo.sql
@@application/shared_components/logic/application_items/app_color_ord_pr.sql
@@application/shared_components/logic/application_items/app_color_ord_rc.sql
@@application/shared_components/logic/application_items/app_color_ord_rj.sql
@@application/shared_components/logic/application_items/app_color_ord_shp.sql
@@application/shared_components/logic/application_items/app_contacts.sql
@@application/shared_components/logic/application_items/app_customers.sql
@@application/shared_components/logic/application_items/app_enquiries.sql
@@application/shared_components/logic/application_items/app_fob_rnd_tolerance.sql
@@application/shared_components/logic/application_items/app_hsn_codes.sql
@@application/shared_components/logic/application_items/app_legal_company.sql
@@application/shared_components/logic/application_items/app_local_curr.sql
@@application/shared_components/logic/application_items/app_local_curr_symbol.sql
@@application/shared_components/logic/application_items/app_om_id.sql
@@application/shared_components/logic/application_items/app_operating_company.sql
@@application/shared_components/logic/application_items/app_orders.sql
@@application/shared_components/logic/application_items/app_products.sql
@@application/shared_components/logic/application_items/app_quote_in.sql
@@application/shared_components/logic/application_items/app_quote_in_symbol.sql
@@application/shared_components/logic/application_items/app_suppliers.sql
@@application/shared_components/logic/application_items/app_sysdate.sql
@@application/shared_components/logic/application_items/app_trans_tenant_id.sql
@@application/shared_components/logic/application_items/app_user_role.sql
@@application/shared_components/logic/application_computations/app_hsn_codes.sql
@@application/shared_components/logic/application_computations/app_orders.sql
@@application/shared_components/logic/application_computations/app_suppliers.sql
@@application/shared_components/logic/application_computations/app_customers.sql
@@application/shared_components/logic/application_computations/app_enquiries.sql
@@application/shared_components/logic/application_computations/app_contacts.sql
@@application/shared_components/logic/application_computations/app_products.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/access_roles.sql
@@application/shared_components/user_interface/lovs/apex_application_mode.sql
@@application/shared_components/user_interface/lovs/apex_application_priv.sql
@@application/shared_components/user_interface/lovs/data_load_charset.sql
@@application/shared_components/user_interface/lovs/data_load_option.sql
@@application/shared_components/user_interface/lovs/date_format_opt.sql
@@application/shared_components/user_interface/lovs/date_format_option.sql
@@application/shared_components/user_interface/lovs/email_username_format.sql
@@application/shared_components/user_interface/lovs/first_row_option.sql
@@application/shared_components/user_interface/lovs/lov_attachment_category.sql
@@application/shared_components/user_interface/lovs/lov_bank.sql
@@application/shared_components/user_interface/lovs/lov_billing_location.sql
@@application/shared_components/user_interface/lovs/lov_board_returns.sql
@@application/shared_components/user_interface/lovs/lov_brand.sql
@@application/shared_components/user_interface/lovs/lov_broker.sql
@@application/shared_components/user_interface/lovs/lov_charges_categories.sql
@@application/shared_components/user_interface/lovs/lov_company_contacts.sql
@@application/shared_components/user_interface/lovs/lov_container_size.sql
@@application/shared_components/user_interface/lovs/lov_container_type.sql
@@application/shared_components/user_interface/lovs/lov_costing_type.sql
@@application/shared_components/user_interface/lovs/lov_costing_type_extra.sql
@@application/shared_components/user_interface/lovs/lov_costing_unit.sql
@@application/shared_components/user_interface/lovs/lov_country.sql
@@application/shared_components/user_interface/lovs/lov_country_code.sql
@@application/shared_components/user_interface/lovs/lov_customer.sql
@@application/shared_components/user_interface/lovs/lov_dashboard_report_type.sql
@@application/shared_components/user_interface/lovs/lov_delivery_location.sql
@@application/shared_components/user_interface/lovs/lov_district.sql
@@application/shared_components/user_interface/lovs/lov_enquiry_status.sql
@@application/shared_components/user_interface/lovs/lov_enq_ord_no.sql
@@application/shared_components/user_interface/lovs/lov_eod_product.sql
@@application/shared_components/user_interface/lovs/lov_expense_type.sql
@@application/shared_components/user_interface/lovs/lov_finance_orders.sql
@@application/shared_components/user_interface/lovs/lov_flag_yn.sql
@@application/shared_components/user_interface/lovs/lov_font_style.sql
@@application/shared_components/user_interface/lovs/lov_highlight_color.sql
@@application/shared_components/user_interface/lovs/lov_inward_no.sql
@@application/shared_components/user_interface/lovs/lov_inward_status.sql
@@application/shared_components/user_interface/lovs/lov_manufacturer.sql
@@application/shared_components/user_interface/lovs/lov_manufacture_type.sql
@@application/shared_components/user_interface/lovs/lov_mode_of_shipment.sql
@@application/shared_components/user_interface/lovs/lov_notes_type.sql
@@application/shared_components/user_interface/lovs/lov_ordered_customer.sql
@@application/shared_components/user_interface/lovs/lov_ordered_supplier.sql
@@application/shared_components/user_interface/lovs/lov_order_status.sql
@@application/shared_components/user_interface/lovs/lov_output_display_attr.sql
@@application/shared_components/user_interface/lovs/lov_output_format.sql
@@application/shared_components/user_interface/lovs/lov_output_type.sql
@@application/shared_components/user_interface/lovs/lov_package_uom.sql
@@application/shared_components/user_interface/lovs/lov_packing_material.sql
@@application/shared_components/user_interface/lovs/lov_packing_material_stock_ig.sql
@@application/shared_components/user_interface/lovs/lov_payment_type.sql
@@application/shared_components/user_interface/lovs/lov_port_of_discharge.sql
@@application/shared_components/user_interface/lovs/lov_port_of_loading.sql
@@application/shared_components/user_interface/lovs/lov_po_costing_unit.sql
@@application/shared_components/user_interface/lovs/lov_po_no.sql
@@application/shared_components/user_interface/lovs/lov_po_status.sql
@@application/shared_components/user_interface/lovs/lov_product.sql
@@application/shared_components/user_interface/lovs/lov_product_category.sql
@@application/shared_components/user_interface/lovs/lov_product_status.sql
@@application/shared_components/user_interface/lovs/lov_product_unit.sql
@@application/shared_components/user_interface/lovs/lov_product_uom.sql
@@application/shared_components/user_interface/lovs/lov_product_user_category.sql
@@application/shared_components/user_interface/lovs/lov_prod_category_type.sql
@@application/shared_components/user_interface/lovs/lov_quote_in.sql
@@application/shared_components/user_interface/lovs/lov_setup_type.sql
@@application/shared_components/user_interface/lovs/lov_state.sql
@@application/shared_components/user_interface/lovs/lov_supplier.sql
@@application/shared_components/user_interface/lovs/lov_supplier_type.sql
@@application/shared_components/user_interface/lovs/lov_weighbridge.sql
@@application/shared_components/user_interface/lovs/lov_weigh_method.sql
@@application/pages/page_groups.sql
@@application/comments.sql
@@application/shared_components/navigation/breadcrumbs/mainmenu.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/page/sb_marquee.sql
@@application/shared_components/user_interface/templates/button/html_button_legacy_apex_5_migration.sql
@@application/shared_components/user_interface/templates/region/sb_tabs_container.sql
@@application/shared_components/user_interface/templates/report/sb_cards.sql
@@application/shared_components/user_interface/templates/report/sb_carousel_report.sql
@@application/shared_components/user_interface/templates/report/sb_badge.sql
@@application/shared_components/user_interface/templates/report/sb_dashboard.sql
@@application/shared_components/user_interface/templates/report/sb_media_list.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/globalization/translations.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/user_interface/shortcuts/delete_confirm_msg.sql
@@application/shared_components/user_interface/shortcuts/ok_to_get_next_prev_pk_value.sql
@@application/shared_components/reports/report_queries/enquiry.sql
@@application/shared_components/reports/report_queries/customer.sql
@@application/shared_components/reports/report_layouts/test.sql
@@application/shared_components/reports/report_layouts/enq.sql
@@application/shared_components/security/authentications/apex.sql
@@application/shared_components/legacy_data_loads/v_temp_proforma.sql
@@application/shared_components/legacy_data_loads/v_supplier_master.sql
@@application/shared_components/legacy_data_loads/v_product_master.sql
@@application/shared_components/data_loads/proforma_bulk_upload.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00002.sql
@@application/pages/page_00003.sql
@@application/pages/page_00004.sql
@@application/pages/page_00005.sql
@@application/pages/page_00006.sql
@@application/pages/page_00007.sql
@@application/pages/page_00008.sql
@@application/pages/page_00009.sql
@@application/pages/page_00010.sql
@@application/pages/page_00011.sql
@@application/pages/page_00012.sql
@@application/pages/page_00013.sql
@@application/pages/page_00014.sql
@@application/pages/page_00015.sql
@@application/pages/page_00016.sql
@@application/pages/page_00017.sql
@@application/pages/page_00018.sql
@@application/pages/page_00019.sql
@@application/pages/page_00020.sql
@@application/pages/page_00021.sql
@@application/pages/page_00022.sql
@@application/pages/page_00023.sql
@@application/pages/page_00024.sql
@@application/pages/page_00025.sql
@@application/pages/page_00026.sql
@@application/pages/page_00027.sql
@@application/pages/page_00028.sql
@@application/pages/page_00029.sql
@@application/pages/page_00030.sql
@@application/pages/page_00031.sql
@@application/pages/page_00032.sql
@@application/pages/page_00033.sql
@@application/pages/page_00034.sql
@@application/pages/page_00035.sql
@@application/pages/page_00036.sql
@@application/pages/page_00037.sql
@@application/pages/page_00038.sql
@@application/pages/page_00039.sql
@@application/pages/page_00040.sql
@@application/pages/page_00041.sql
@@application/pages/page_00042.sql
@@application/pages/page_00043.sql
@@application/pages/page_00044.sql
@@application/pages/page_00045.sql
@@application/pages/page_00046.sql
@@application/pages/page_00047.sql
@@application/pages/page_00048.sql
@@application/pages/page_00049.sql
@@application/pages/page_00050.sql
@@application/pages/page_00051.sql
@@application/pages/page_00052.sql
@@application/pages/page_00053.sql
@@application/pages/page_00054.sql
@@application/pages/page_00055.sql
@@application/pages/page_00056.sql
@@application/pages/page_00057.sql
@@application/pages/page_00058.sql
@@application/pages/page_00059.sql
@@application/pages/page_00060.sql
@@application/pages/page_00061.sql
@@application/pages/page_00062.sql
@@application/pages/page_00063.sql
@@application/pages/page_00064.sql
@@application/pages/page_00065.sql
@@application/pages/page_00066.sql
@@application/pages/page_00067.sql
@@application/pages/page_00068.sql
@@application/pages/page_00069.sql
@@application/pages/page_00070.sql
@@application/pages/page_00071.sql
@@application/pages/page_00072.sql
@@application/pages/page_00073.sql
@@application/pages/page_00074.sql
@@application/pages/page_00075.sql
@@application/pages/page_00076.sql
@@application/pages/page_00077.sql
@@application/pages/page_00078.sql
@@application/pages/page_00079.sql
@@application/pages/page_00080.sql
@@application/pages/page_00081.sql
@@application/pages/page_00082.sql
@@application/pages/page_00083.sql
@@application/pages/page_00084.sql
@@application/pages/page_00085.sql
@@application/pages/page_00086.sql
@@application/pages/page_00087.sql
@@application/pages/page_00088.sql
@@application/pages/page_00089.sql
@@application/pages/page_00090.sql
@@application/pages/page_00091.sql
@@application/pages/page_00092.sql
@@application/pages/page_00093.sql
@@application/pages/page_00094.sql
@@application/pages/page_00095.sql
@@application/pages/page_00096.sql
@@application/pages/page_00097.sql
@@application/pages/page_00098.sql
@@application/pages/page_00099.sql
@@application/pages/page_00100.sql
@@application/pages/page_00101.sql
@@application/pages/page_00102.sql
@@application/pages/page_00110.sql
@@application/pages/page_00111.sql
@@application/pages/page_01000.sql
@@application/pages/page_01001.sql
@@application/pages/page_09000.sql
@@application/pages/page_10000.sql
@@application/pages/page_10010.sql
@@application/pages/page_10011.sql
@@application/pages/page_10012.sql
@@application/pages/page_10013.sql
@@application/pages/page_10014.sql
@@application/end_environment.sql
