prompt --application/shared_components/reports/report_layouts/enq
begin
--   Manifest
--     REPORT LAYOUT: enq
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.15'
,p_default_workspace_id=>7965342552622829
,p_default_application_id=>200
,p_default_id_offset=>32162224829641601
,p_default_owner=>'SAARTHIDEV'
);
wwv_flow_imp.g_varchar2_table := wwv_flow_imp.empty_varchar2_table;
wwv_flow_imp.g_varchar2_table(1) := '<?xml version="1.0" encoding="UTF-8"?>'||wwv_flow.LF||
'<!--Designed and generated by Altova StyleVision Enterprise E';
wwv_flow_imp.g_varchar2_table(2) := 'dition 2017 sp2 - see http://www.altova.com/stylevision for more information.-->'||wwv_flow.LF||
'<xsl:stylesheet ver';
wwv_flow_imp.g_varchar2_table(3) := 'sion="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:altova="http://www.altova.com" xml';
wwv_flow_imp.g_varchar2_table(4) := 'ns:altova-xfi="http://www.altova.com/xslt-extensions/xbrl" xmlns:altovaext="http://www.altova.com/xs';
wwv_flow_imp.g_varchar2_table(5) := 'lt-extensions" xmlns:array="http://www.w3.org/2005/xpath-functions/array" xmlns:clitype="clitype" xm';
wwv_flow_imp.g_varchar2_table(6) := 'lns:fn="http://www.w3.org/2005/xpath-functions" xmlns:iso4217="http://www.xbrl.org/2003/iso4217" xml';
wwv_flow_imp.g_varchar2_table(7) := 'ns:ix="http://www.xbrl.org/2008/inlineXBRL" xmlns:java="java" xmlns:link="http://www.xbrl.org/2003/l';
wwv_flow_imp.g_varchar2_table(8) := 'inkbase" xmlns:map="http://www.w3.org/2005/xpath-functions/map" xmlns:math="http://www.w3.org/2005/x';
wwv_flow_imp.g_varchar2_table(9) := 'path-functions/math" xmlns:sps="http://www.altova.com/StyleVision/user-xpath-functions" xmlns:xbrldi';
wwv_flow_imp.g_varchar2_table(10) := '="http://xbrl.org/2006/xbrldi" xmlns:xbrli="http://www.xbrl.org/2003/instance" xmlns:xff="http://www';
wwv_flow_imp.g_varchar2_table(11) := '.xbrl.org/2010/function/formula" xmlns:xfi="http://www.xbrl.org/2008/function/instance" xmlns:xlink=';
wwv_flow_imp.g_varchar2_table(12) := '"http://www.w3.org/1999/xlink" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.';
wwv_flow_imp.g_varchar2_table(13) := 'org/2001/XMLSchema-instance" xmlns:fo="http://www.w3.org/1999/XSL/Format" xmlns:svg="http://www.w3.o';
wwv_flow_imp.g_varchar2_table(14) := 'rg/2000/svg" exclude-result-prefixes="altova altova-xfi altovaext array clitype fn iso4217 ix java l';
wwv_flow_imp.g_varchar2_table(15) := 'ink map math sps xbrldi xbrli xff xfi xlink xs xsi">'||wwv_flow.LF||
'	<xsl:output version="1.0" method="xml" encodin';
wwv_flow_imp.g_varchar2_table(16) := 'g="UTF-8" indent="no"/>'||wwv_flow.LF||
'	<xsl:param name="SV_OutputFormat" select="''PDF''"/>'||wwv_flow.LF||
'	<xsl:variable name="XML';
wwv_flow_imp.g_varchar2_table(17) := '" select="/"/>'||wwv_flow.LF||
'	<xsl:variable name="fo:layout-master-set">'||wwv_flow.LF||
'		<fo:layout-master-set>'||wwv_flow.LF||
'			<fo:simple-pa';
wwv_flow_imp.g_varchar2_table(18) := 'ge-master master-name="page-master-0-even" margin-left="0.6in" margin-right="0.6in" page-height="11.';
wwv_flow_imp.g_varchar2_table(19) := '693in" page-width="8.268in" margin-top="0.492in" margin-bottom="0.492in">'||wwv_flow.LF||
'				<fo:region-body margin';
wwv_flow_imp.g_varchar2_table(20) := '-top="1.01in" margin-bottom="1.01in" column-count="1" column-gap="0.50in"/>'||wwv_flow.LF||
'				<fo:region-before re';
wwv_flow_imp.g_varchar2_table(21) := 'gion-name="even-page-header" overflow="hidden" extent="1.01in"/>'||wwv_flow.LF||
'				<fo:region-after region-name="e';
wwv_flow_imp.g_varchar2_table(22) := 'ven-page-footer" overflow="hidden" extent="1.01in"/>'||wwv_flow.LF||
'			</fo:simple-page-master>'||wwv_flow.LF||
'			<fo:simple-page-';
wwv_flow_imp.g_varchar2_table(23) := 'master master-name="page-master-0-odd" margin-left="0.6in" margin-right="0.6in" page-height="11.693i';
wwv_flow_imp.g_varchar2_table(24) := 'n" page-width="8.268in" margin-top="0.492in" margin-bottom="0.492in">'||wwv_flow.LF||
'				<fo:region-body margin-top';
wwv_flow_imp.g_varchar2_table(25) := '="1.01in" margin-bottom="1.01in" column-count="1" column-gap="0.50in"/>'||wwv_flow.LF||
'				<fo:region-before region';
wwv_flow_imp.g_varchar2_table(26) := '-name="odd-page-header" overflow="hidden" extent="1.01in"/>'||wwv_flow.LF||
'				<fo:region-after region-name="odd-pa';
wwv_flow_imp.g_varchar2_table(27) := 'ge-footer" overflow="hidden" extent="1.01in"/>'||wwv_flow.LF||
'			</fo:simple-page-master>'||wwv_flow.LF||
'			<fo:page-sequence-mast';
wwv_flow_imp.g_varchar2_table(28) := 'er master-name="page-master-0">'||wwv_flow.LF||
'				<fo:repeatable-page-master-alternatives>'||wwv_flow.LF||
'					<fo:conditional-pa';
wwv_flow_imp.g_varchar2_table(29) := 'ge-master-reference master-reference="page-master-0-even" odd-or-even="even"/>'||wwv_flow.LF||
'					<fo:conditional-';
wwv_flow_imp.g_varchar2_table(30) := 'page-master-reference master-reference="page-master-0-odd" odd-or-even="odd"/>'||wwv_flow.LF||
'				</fo:repeatable-p';
wwv_flow_imp.g_varchar2_table(31) := 'age-master-alternatives>'||wwv_flow.LF||
'			</fo:page-sequence-master>'||wwv_flow.LF||
'		</fo:layout-master-set>'||wwv_flow.LF||
'	</xsl:variable>'||wwv_flow.LF||
'	<';
wwv_flow_imp.g_varchar2_table(32) := 'xsl:variable name="altova:nPxPerIn" select="96"/>'||wwv_flow.LF||
'	<xsl:template match="/">'||wwv_flow.LF||
'		<fo:root>'||wwv_flow.LF||
'			<xsl:copy';
wwv_flow_imp.g_varchar2_table(33) := '-of select="$fo:layout-master-set"/>'||wwv_flow.LF||
'			<fo:declarations>'||wwv_flow.LF||
'				<x:xmpmeta xmlns:x="adobe:ns:meta/">'||wwv_flow.LF||
'	';
wwv_flow_imp.g_varchar2_table(34) := '				<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">'||wwv_flow.LF||
'						<rdf:Description rdf:abo';
wwv_flow_imp.g_varchar2_table(35) := 'ut="" xmlns:xmp="http://ns.adobe.com/xap/1.0/">'||wwv_flow.LF||
'							<xmp:CreatorTool>Altova StyleVision Enterpris';
wwv_flow_imp.g_varchar2_table(36) := 'e Edition 2017 sp2 (http://www.altova.com)</xmp:CreatorTool>'||wwv_flow.LF||
'						</rdf:Description>'||wwv_flow.LF||
'					</rdf:RDF';
wwv_flow_imp.g_varchar2_table(37) := '>'||wwv_flow.LF||
'				</x:xmpmeta>'||wwv_flow.LF||
'			</fo:declarations>'||wwv_flow.LF||
'			<fo:page-sequence force-page-count="no-force" master-ref';
wwv_flow_imp.g_varchar2_table(38) := 'erence="page-master-0" initial-page-number="auto" format="1">'||wwv_flow.LF||
'				<fo:static-content flow-name="odd-';
wwv_flow_imp.g_varchar2_table(39) := 'page-header">'||wwv_flow.LF||
'					<fo:block-container overflow="hidden" display-align="before">'||wwv_flow.LF||
'						<fo:block>'||wwv_flow.LF||
'		';
wwv_flow_imp.g_varchar2_table(40) := '					<fo:inline-container>'||wwv_flow.LF||
'								<fo:block>'||wwv_flow.LF||
'									<xsl:text>&#x200B;</xsl:text>'||wwv_flow.LF||
'								</fo:bl';
wwv_flow_imp.g_varchar2_table(41) := 'ock>'||wwv_flow.LF||
'							</fo:inline-container>'||wwv_flow.LF||
'							<fo:table width="100%" table-layout="fixed" border-spacing';
wwv_flow_imp.g_varchar2_table(42) := '="2pt">'||wwv_flow.LF||
'								<fo:table-column column-width="90%"/>'||wwv_flow.LF||
'								<xsl:variable name="altova:CurrContext';
wwv_flow_imp.g_varchar2_table(43) := 'Grid_1" select="."/>'||wwv_flow.LF||
'								<fo:table-body start-indent="0pt">'||wwv_flow.LF||
'									<xsl:variable name="altova:';
wwv_flow_imp.g_varchar2_table(44) := 'tablerows">'||wwv_flow.LF||
'										<fo:table-row>'||wwv_flow.LF||
'											<fo:table-cell font-size="10pt" padding="0" display-';
wwv_flow_imp.g_varchar2_table(45) := 'align="center">'||wwv_flow.LF||
'												<fo:block text-align="left">'||wwv_flow.LF||
'													<fo:external-graphic>'||wwv_flow.LF||
'								';
wwv_flow_imp.g_varchar2_table(46) := '						<xsl:attribute name="src">'||wwv_flow.LF||
'															<xsl:text>url(</xsl:text>'||wwv_flow.LF||
'															<xsl:call-t';
wwv_flow_imp.g_varchar2_table(47) := 'emplate name="altova:double-backslash">'||wwv_flow.LF||
'																<xsl:with-param name="text">'||wwv_flow.LF||
'															';
wwv_flow_imp.g_varchar2_table(48) := '		<xsl:value-of select="string(&apos;../../../apache-tomcat-8.5.13/apache-tomcat-8.5.13/webapps/i/Ja';
wwv_flow_imp.g_varchar2_table(49) := 'nuzLogo.png&apos;)"/>'||wwv_flow.LF||
'																</xsl:with-param>'||wwv_flow.LF||
'																<xsl:with-param name="text-l';
wwv_flow_imp.g_varchar2_table(50) := 'ength">'||wwv_flow.LF||
'																	<xsl:value-of select="string-length(string(&apos;../../../apache-tomcat-8.5';
wwv_flow_imp.g_varchar2_table(51) := '.13/apache-tomcat-8.5.13/webapps/i/JanuzLogo.png&apos;))"/>'||wwv_flow.LF||
'																</xsl:with-param>'||wwv_flow.LF||
'						';
wwv_flow_imp.g_varchar2_table(52) := '									</xsl:call-template>'||wwv_flow.LF||
'															<xsl:text>)</xsl:text>'||wwv_flow.LF||
'														</xsl:attribute>'||wwv_flow.LF||
'	';
wwv_flow_imp.g_varchar2_table(53) := '												</fo:external-graphic>'||wwv_flow.LF||
'													<fo:inline>'||wwv_flow.LF||
'														<xsl:text>&#x200B;</xsl:te';
wwv_flow_imp.g_varchar2_table(54) := 'xt>'||wwv_flow.LF||
'													</fo:inline>'||wwv_flow.LF||
'												</fo:block>'||wwv_flow.LF||
'											</fo:table-cell>'||wwv_flow.LF||
'										</fo:tab';
wwv_flow_imp.g_varchar2_table(55) := 'le-row>'||wwv_flow.LF||
'										<fo:table-row>'||wwv_flow.LF||
'											<fo:table-cell padding="0" display-align="center">'||wwv_flow.LF||
'					';
wwv_flow_imp.g_varchar2_table(56) := '							<fo:block text-align="left">'||wwv_flow.LF||
'													<fo:block text-align="center">'||wwv_flow.LF||
'														<fo:le';
wwv_flow_imp.g_varchar2_table(57) := 'ader leader-pattern="rule" rule-thickness="1" leader-length="100%" color="black"/>'||wwv_flow.LF||
'													</fo';
wwv_flow_imp.g_varchar2_table(58) := ':block>'||wwv_flow.LF||
'												</fo:block>'||wwv_flow.LF||
'											</fo:table-cell>'||wwv_flow.LF||
'										</fo:table-row>'||wwv_flow.LF||
'									</xsl';
wwv_flow_imp.g_varchar2_table(59) := ':variable>'||wwv_flow.LF||
'									<xsl:choose>'||wwv_flow.LF||
'										<xsl:when test="string($altova:tablerows)">'||wwv_flow.LF||
'											<x';
wwv_flow_imp.g_varchar2_table(60) := 'sl:copy-of select="$altova:tablerows"/>'||wwv_flow.LF||
'										</xsl:when>'||wwv_flow.LF||
'										<xsl:otherwise>'||wwv_flow.LF||
'											<';
wwv_flow_imp.g_varchar2_table(61) := 'fo:table-row>'||wwv_flow.LF||
'												<fo:table-cell>'||wwv_flow.LF||
'													<fo:block/>'||wwv_flow.LF||
'												</fo:table-cell>'||wwv_flow.LF||
'				';
wwv_flow_imp.g_varchar2_table(62) := '							</fo:table-row>'||wwv_flow.LF||
'										</xsl:otherwise>'||wwv_flow.LF||
'									</xsl:choose>'||wwv_flow.LF||
'								</fo:table-body>'||wwv_flow.LF||
'		';
wwv_flow_imp.g_varchar2_table(63) := '					</fo:table>'||wwv_flow.LF||
'						</fo:block>'||wwv_flow.LF||
'					</fo:block-container>'||wwv_flow.LF||
'				</fo:static-content>'||wwv_flow.LF||
'				<fo:stati';
wwv_flow_imp.g_varchar2_table(64) := 'c-content flow-name="even-page-header">'||wwv_flow.LF||
'					<fo:block-container overflow="hidden" display-align="be';
wwv_flow_imp.g_varchar2_table(65) := 'fore">'||wwv_flow.LF||
'						<fo:block>'||wwv_flow.LF||
'							<fo:inline-container>'||wwv_flow.LF||
'								<fo:block>'||wwv_flow.LF||
'									<xsl:text>&#x200B;<';
wwv_flow_imp.g_varchar2_table(66) := '/xsl:text>'||wwv_flow.LF||
'								</fo:block>'||wwv_flow.LF||
'							</fo:inline-container>'||wwv_flow.LF||
'							<fo:table width="100%" table-lay';
wwv_flow_imp.g_varchar2_table(67) := 'out="fixed" border-spacing="2pt">'||wwv_flow.LF||
'								<fo:table-column column-width="90%"/>'||wwv_flow.LF||
'								<xsl:variabl';
wwv_flow_imp.g_varchar2_table(68) := 'e name="altova:CurrContextGrid_1" select="."/>'||wwv_flow.LF||
'								<fo:table-body start-indent="0pt">'||wwv_flow.LF||
'									<';
wwv_flow_imp.g_varchar2_table(69) := 'xsl:variable name="altova:tablerows">'||wwv_flow.LF||
'										<fo:table-row>'||wwv_flow.LF||
'											<fo:table-cell font-size="';
wwv_flow_imp.g_varchar2_table(70) := '10pt" padding="0" display-align="center">'||wwv_flow.LF||
'												<fo:block text-align="left">'||wwv_flow.LF||
'													<fo:';
wwv_flow_imp.g_varchar2_table(71) := 'external-graphic>'||wwv_flow.LF||
'														<xsl:attribute name="src">'||wwv_flow.LF||
'															<xsl:text>url(</xsl:text>'||wwv_flow.LF||
'';
wwv_flow_imp.g_varchar2_table(72) := '															<xsl:call-template name="altova:double-backslash">'||wwv_flow.LF||
'																<xsl:with-param na';
wwv_flow_imp.g_varchar2_table(73) := 'me="text">'||wwv_flow.LF||
'																	<xsl:value-of select="string(&apos;../../../apache-tomcat-8.5.13/apache-';
wwv_flow_imp.g_varchar2_table(74) := 'tomcat-8.5.13/webapps/i/JanuzLogo.png&apos;)"/>'||wwv_flow.LF||
'																</xsl:with-param>'||wwv_flow.LF||
'																<x';
wwv_flow_imp.g_varchar2_table(75) := 'sl:with-param name="text-length">'||wwv_flow.LF||
'																	<xsl:value-of select="string-length(string(&apos;';
wwv_flow_imp.g_varchar2_table(76) := '../../../apache-tomcat-8.5.13/apache-tomcat-8.5.13/webapps/i/JanuzLogo.png&apos;))"/>'||wwv_flow.LF||
'														';
wwv_flow_imp.g_varchar2_table(77) := '		</xsl:with-param>'||wwv_flow.LF||
'															</xsl:call-template>'||wwv_flow.LF||
'															<xsl:text>)</xsl:text>'||wwv_flow.LF||
'						';
wwv_flow_imp.g_varchar2_table(78) := '								</xsl:attribute>'||wwv_flow.LF||
'													</fo:external-graphic>'||wwv_flow.LF||
'													<fo:inline>'||wwv_flow.LF||
'														';
wwv_flow_imp.g_varchar2_table(79) := '<xsl:text>&#x200B;</xsl:text>'||wwv_flow.LF||
'													</fo:inline>'||wwv_flow.LF||
'												</fo:block>'||wwv_flow.LF||
'											</fo:tabl';
wwv_flow_imp.g_varchar2_table(80) := 'e-cell>'||wwv_flow.LF||
'										</fo:table-row>'||wwv_flow.LF||
'										<fo:table-row>'||wwv_flow.LF||
'											<fo:table-cell padding="0" dis';
wwv_flow_imp.g_varchar2_table(81) := 'play-align="center">'||wwv_flow.LF||
'												<fo:block text-align="left">'||wwv_flow.LF||
'													<fo:block text-align="cen';
wwv_flow_imp.g_varchar2_table(82) := 'ter">'||wwv_flow.LF||
'														<fo:leader leader-pattern="rule" rule-thickness="1" leader-length="100%" color="';
wwv_flow_imp.g_varchar2_table(83) := 'black"/>'||wwv_flow.LF||
'													</fo:block>'||wwv_flow.LF||
'												</fo:block>'||wwv_flow.LF||
'											</fo:table-cell>'||wwv_flow.LF||
'										</fo';
wwv_flow_imp.g_varchar2_table(84) := ':table-row>'||wwv_flow.LF||
'									</xsl:variable>'||wwv_flow.LF||
'									<xsl:choose>'||wwv_flow.LF||
'										<xsl:when test="string($altova:';
wwv_flow_imp.g_varchar2_table(85) := 'tablerows)">'||wwv_flow.LF||
'											<xsl:copy-of select="$altova:tablerows"/>'||wwv_flow.LF||
'										</xsl:when>'||wwv_flow.LF||
'										<x';
wwv_flow_imp.g_varchar2_table(86) := 'sl:otherwise>'||wwv_flow.LF||
'											<fo:table-row>'||wwv_flow.LF||
'												<fo:table-cell>'||wwv_flow.LF||
'													<fo:block/>'||wwv_flow.LF||
'							';
wwv_flow_imp.g_varchar2_table(87) := '					</fo:table-cell>'||wwv_flow.LF||
'											</fo:table-row>'||wwv_flow.LF||
'										</xsl:otherwise>'||wwv_flow.LF||
'									</xsl:choose>'||wwv_flow.LF||
'	';
wwv_flow_imp.g_varchar2_table(88) := '							</fo:table-body>'||wwv_flow.LF||
'							</fo:table>'||wwv_flow.LF||
'						</fo:block>'||wwv_flow.LF||
'					</fo:block-container>'||wwv_flow.LF||
'				</fo:sta';
wwv_flow_imp.g_varchar2_table(89) := 'tic-content>'||wwv_flow.LF||
'				<fo:static-content flow-name="odd-page-footer">'||wwv_flow.LF||
'					<fo:block-container height="1.';
wwv_flow_imp.g_varchar2_table(90) := '01in" overflow="hidden" display-align="after">'||wwv_flow.LF||
'						<fo:block>'||wwv_flow.LF||
'							<fo:inline-container>'||wwv_flow.LF||
'							';
wwv_flow_imp.g_varchar2_table(91) := '	<fo:block>'||wwv_flow.LF||
'									<xsl:text>&#x200B;</xsl:text>'||wwv_flow.LF||
'								</fo:block>'||wwv_flow.LF||
'							</fo:inline-container>';
wwv_flow_imp.g_varchar2_table(92) := ''||wwv_flow.LF||
'							<fo:table width="100%" table-layout="fixed" border-spacing="2pt">'||wwv_flow.LF||
'								<fo:table-column c';
wwv_flow_imp.g_varchar2_table(93) := 'olumn-width="90%"/>'||wwv_flow.LF||
'								<fo:table-column column-width="10%"/>'||wwv_flow.LF||
'								<xsl:variable name="altova';
wwv_flow_imp.g_varchar2_table(94) := ':CurrContextGrid_2" select="."/>'||wwv_flow.LF||
'								<fo:table-body start-indent="0pt">'||wwv_flow.LF||
'									<xsl:variable n';
wwv_flow_imp.g_varchar2_table(95) := 'ame="altova:tablerows">'||wwv_flow.LF||
'										<fo:table-row>'||wwv_flow.LF||
'											<fo:table-cell number-columns-spanned="2';
wwv_flow_imp.g_varchar2_table(96) := '" padding="0" display-align="center">'||wwv_flow.LF||
'												<fo:block text-align="left">'||wwv_flow.LF||
'													<fo:bloc';
wwv_flow_imp.g_varchar2_table(97) := 'k text-align="center">'||wwv_flow.LF||
'														<fo:leader leader-pattern="rule" rule-thickness="1" leader-leng';
wwv_flow_imp.g_varchar2_table(98) := 'th="100%" color="black"/>'||wwv_flow.LF||
'													</fo:block>'||wwv_flow.LF||
'												</fo:block>'||wwv_flow.LF||
'											</fo:table-cel';
wwv_flow_imp.g_varchar2_table(99) := 'l>'||wwv_flow.LF||
'										</fo:table-row>'||wwv_flow.LF||
'										<fo:table-row>'||wwv_flow.LF||
'											<fo:table-cell font-size="10pt" pad';
wwv_flow_imp.g_varchar2_table(100) := 'ding="0" display-align="center">'||wwv_flow.LF||
'												<fo:block text-align="left">'||wwv_flow.LF||
'													<fo:inline>'||wwv_flow.LF||
'	';
wwv_flow_imp.g_varchar2_table(101) := unistr('													<xsl:text>305, Mahindra Chambers, 619/28, W.T. Patil Marg, Chembur \FD3EEast\FD3F, Mumbai\2010400 0');
wwv_flow_imp.g_varchar2_table(102) := unistr('71. INDIA&#160; Tel. \FD3E022\FD3F 25205488 / Fax \FD3E022\FD3F 25215488/ e: januz@januzuniversal.in</xsl:text>'||wwv_flow.LF||
'				');
wwv_flow_imp.g_varchar2_table(103) := '									</fo:inline>'||wwv_flow.LF||
'												</fo:block>'||wwv_flow.LF||
'											</fo:table-cell>'||wwv_flow.LF||
'											<fo:table-cell ';
wwv_flow_imp.g_varchar2_table(104) := 'font-size="10pt" padding="0" display-align="center">'||wwv_flow.LF||
'												<fo:block text-align="right">'||wwv_flow.LF||
'					';
wwv_flow_imp.g_varchar2_table(105) := '								<fo:inline font-weight="bold">'||wwv_flow.LF||
'														<xsl:text>Page: </xsl:text>'||wwv_flow.LF||
'													</fo:i';
wwv_flow_imp.g_varchar2_table(106) := 'nline>'||wwv_flow.LF||
'													<fo:page-number font-weight="bold"/>'||wwv_flow.LF||
'												</fo:block>'||wwv_flow.LF||
'											</fo:tab';
wwv_flow_imp.g_varchar2_table(107) := 'le-cell>'||wwv_flow.LF||
'										</fo:table-row>'||wwv_flow.LF||
'									</xsl:variable>'||wwv_flow.LF||
'									<xsl:choose>'||wwv_flow.LF||
'										<xsl:whe';
wwv_flow_imp.g_varchar2_table(108) := 'n test="string($altova:tablerows)">'||wwv_flow.LF||
'											<xsl:copy-of select="$altova:tablerows"/>'||wwv_flow.LF||
'										<';
wwv_flow_imp.g_varchar2_table(109) := '/xsl:when>'||wwv_flow.LF||
'										<xsl:otherwise>'||wwv_flow.LF||
'											<fo:table-row>'||wwv_flow.LF||
'												<fo:table-cell>'||wwv_flow.LF||
'									';
wwv_flow_imp.g_varchar2_table(110) := '				<fo:block/>'||wwv_flow.LF||
'												</fo:table-cell>'||wwv_flow.LF||
'											</fo:table-row>'||wwv_flow.LF||
'										</xsl:otherwise>'||wwv_flow.LF||
'	';
wwv_flow_imp.g_varchar2_table(111) := '								</xsl:choose>'||wwv_flow.LF||
'								</fo:table-body>'||wwv_flow.LF||
'							</fo:table>'||wwv_flow.LF||
'						</fo:block>'||wwv_flow.LF||
'					</fo:block-';
wwv_flow_imp.g_varchar2_table(112) := 'container>'||wwv_flow.LF||
'				</fo:static-content>'||wwv_flow.LF||
'				<fo:static-content flow-name="even-page-footer">'||wwv_flow.LF||
'					<fo:bl';
wwv_flow_imp.g_varchar2_table(113) := 'ock-container height="1.01in" overflow="hidden" display-align="after">'||wwv_flow.LF||
'						<fo:block>'||wwv_flow.LF||
'							<fo:i';
wwv_flow_imp.g_varchar2_table(114) := 'nline-container>'||wwv_flow.LF||
'								<fo:block>'||wwv_flow.LF||
'									<xsl:text>&#x200B;</xsl:text>'||wwv_flow.LF||
'								</fo:block>'||wwv_flow.LF||
'					';
wwv_flow_imp.g_varchar2_table(115) := '		</fo:inline-container>'||wwv_flow.LF||
'							<fo:table width="100%" table-layout="fixed" border-spacing="2pt">'||wwv_flow.LF||
'		';
wwv_flow_imp.g_varchar2_table(116) := '						<fo:table-column column-width="90%"/>'||wwv_flow.LF||
'								<fo:table-column column-width="10%"/>'||wwv_flow.LF||
'								<x';
wwv_flow_imp.g_varchar2_table(117) := 'sl:variable name="altova:CurrContextGrid_2" select="."/>'||wwv_flow.LF||
'								<fo:table-body start-indent="0pt">'||wwv_flow.LF||
'';
wwv_flow_imp.g_varchar2_table(118) := '									<xsl:variable name="altova:tablerows">'||wwv_flow.LF||
'										<fo:table-row>'||wwv_flow.LF||
'											<fo:table-cell n';
wwv_flow_imp.g_varchar2_table(119) := 'umber-columns-spanned="2" padding="0" display-align="center">'||wwv_flow.LF||
'												<fo:block text-align="left';
wwv_flow_imp.g_varchar2_table(120) := '">'||wwv_flow.LF||
'													<fo:block text-align="center">'||wwv_flow.LF||
'														<fo:leader leader-pattern="rule" rule-t';
wwv_flow_imp.g_varchar2_table(121) := 'hickness="1" leader-length="100%" color="black"/>'||wwv_flow.LF||
'													</fo:block>'||wwv_flow.LF||
'												</fo:block>'||wwv_flow.LF||
'	';
wwv_flow_imp.g_varchar2_table(122) := '										</fo:table-cell>'||wwv_flow.LF||
'										</fo:table-row>'||wwv_flow.LF||
'										<fo:table-row>'||wwv_flow.LF||
'											<fo:table-c';
wwv_flow_imp.g_varchar2_table(123) := 'ell font-size="10pt" padding="0" display-align="center">'||wwv_flow.LF||
'												<fo:block text-align="left">'||wwv_flow.LF||
'		';
wwv_flow_imp.g_varchar2_table(124) := '											<fo:inline>'||wwv_flow.LF||
'														<xsl:text>305, Mahindra Chambers, 619/28, W.T. Patil Marg, Chem';
wwv_flow_imp.g_varchar2_table(125) := unistr('bur \FD3EEast\FD3F, Mumbai\2010400 071. INDIA&#160; Tel. \FD3E022\FD3F 25205488 / Fax \FD3E022\FD3F 25215488/ e: januz@januzuniv');
wwv_flow_imp.g_varchar2_table(126) := 'ersal.in</xsl:text>'||wwv_flow.LF||
'													</fo:inline>'||wwv_flow.LF||
'												</fo:block>'||wwv_flow.LF||
'											</fo:table-cell>'||wwv_flow.LF||
'		';
wwv_flow_imp.g_varchar2_table(127) := '									<fo:table-cell font-size="10pt" padding="0" display-align="center">'||wwv_flow.LF||
'												<fo:block t';
wwv_flow_imp.g_varchar2_table(128) := 'ext-align="right">'||wwv_flow.LF||
'													<fo:inline font-weight="bold">'||wwv_flow.LF||
'														<xsl:text>Page: </xsl:t';
wwv_flow_imp.g_varchar2_table(129) := 'ext>'||wwv_flow.LF||
'													</fo:inline>'||wwv_flow.LF||
'													<fo:page-number font-weight="bold"/>'||wwv_flow.LF||
'												</fo:bl';
wwv_flow_imp.g_varchar2_table(130) := 'ock>'||wwv_flow.LF||
'											</fo:table-cell>'||wwv_flow.LF||
'										</fo:table-row>'||wwv_flow.LF||
'									</xsl:variable>'||wwv_flow.LF||
'									<xsl:ch';
wwv_flow_imp.g_varchar2_table(131) := 'oose>'||wwv_flow.LF||
'										<xsl:when test="string($altova:tablerows)">'||wwv_flow.LF||
'											<xsl:copy-of select="$altova:';
wwv_flow_imp.g_varchar2_table(132) := 'tablerows"/>'||wwv_flow.LF||
'										</xsl:when>'||wwv_flow.LF||
'										<xsl:otherwise>'||wwv_flow.LF||
'											<fo:table-row>'||wwv_flow.LF||
'												<';
wwv_flow_imp.g_varchar2_table(133) := 'fo:table-cell>'||wwv_flow.LF||
'													<fo:block/>'||wwv_flow.LF||
'												</fo:table-cell>'||wwv_flow.LF||
'											</fo:table-row>'||wwv_flow.LF||
'				';
wwv_flow_imp.g_varchar2_table(134) := '						</xsl:otherwise>'||wwv_flow.LF||
'									</xsl:choose>'||wwv_flow.LF||
'								</fo:table-body>'||wwv_flow.LF||
'							</fo:table>'||wwv_flow.LF||
'						</fo';
wwv_flow_imp.g_varchar2_table(135) := ':block>'||wwv_flow.LF||
'					</fo:block-container>'||wwv_flow.LF||
'				</fo:static-content>'||wwv_flow.LF||
'				<fo:flow flow-name="xsl-region-body"';
wwv_flow_imp.g_varchar2_table(136) := '>'||wwv_flow.LF||
'					<fo:block>'||wwv_flow.LF||
'						<fo:block>'||wwv_flow.LF||
'							<fo:leader leader-pattern="space"/>'||wwv_flow.LF||
'						</fo:block>'||wwv_flow.LF||
'				';
wwv_flow_imp.g_varchar2_table(137) := '		<fo:inline-container>'||wwv_flow.LF||
'							<fo:block>'||wwv_flow.LF||
'								<xsl:text>&#x200B;</xsl:text>'||wwv_flow.LF||
'							</fo:block>'||wwv_flow.LF||
'	';
wwv_flow_imp.g_varchar2_table(138) := '					</fo:inline-container>'||wwv_flow.LF||
'						<fo:block text-align="center" margin-right="100% - 100%" margin="0';
wwv_flow_imp.g_varchar2_table(139) := unistr('pt">'||wwv_flow.LF||
'							<fo:inline font-weight="bold" text-decoration="underline">'||wwv_flow.LF||
'								<xsl:text>PROFORMA\00A0IN');
wwv_flow_imp.g_varchar2_table(140) := 'VOICE</xsl:text>'||wwv_flow.LF||
'							</fo:inline>'||wwv_flow.LF||
'						</fo:block>'||wwv_flow.LF||
'						<fo:inline>'||wwv_flow.LF||
'							<xsl:text>To,</xsl:t';
wwv_flow_imp.g_varchar2_table(141) := 'ext>'||wwv_flow.LF||
'						</fo:inline>'||wwv_flow.LF||
'						<fo:block/>'||wwv_flow.LF||
'						<xsl:for-each select="$XML">'||wwv_flow.LF||
'							<xsl:for-each se';
wwv_flow_imp.g_varchar2_table(142) := 'lect="DOCUMENT">'||wwv_flow.LF||
'								<xsl:for-each select="DATA">'||wwv_flow.LF||
'									<xsl:for-each select="ROWSET2">'||wwv_flow.LF||
'					';
wwv_flow_imp.g_varchar2_table(143) := '					<xsl:for-each select="ROWSET2_ROW">'||wwv_flow.LF||
'											<xsl:for-each select="CM_NAME">'||wwv_flow.LF||
'												<xsl';
wwv_flow_imp.g_varchar2_table(144) := ':variable name="value-of-template_3">'||wwv_flow.LF||
'													<xsl:apply-templates/>'||wwv_flow.LF||
'												</xsl:variable';
wwv_flow_imp.g_varchar2_table(145) := '>'||wwv_flow.LF||
'												<xsl:choose>'||wwv_flow.LF||
'													<xsl:when test="contains(string($value-of-template_3),''&#x20';
wwv_flow_imp.g_varchar2_table(146) := '0B;'')">'||wwv_flow.LF||
'														<fo:block>'||wwv_flow.LF||
'															<xsl:copy-of select="$value-of-template_3"/>'||wwv_flow.LF||
'							';
wwv_flow_imp.g_varchar2_table(147) := '							</fo:block>'||wwv_flow.LF||
'													</xsl:when>'||wwv_flow.LF||
'													<xsl:otherwise>'||wwv_flow.LF||
'														<fo:inline>'||wwv_flow.LF||
'	';
wwv_flow_imp.g_varchar2_table(148) := '														<xsl:copy-of select="$value-of-template_3"/>'||wwv_flow.LF||
'														</fo:inline>'||wwv_flow.LF||
'													<';
wwv_flow_imp.g_varchar2_table(149) := '/xsl:otherwise>'||wwv_flow.LF||
'												</xsl:choose>'||wwv_flow.LF||
'											</xsl:for-each>'||wwv_flow.LF||
'										</xsl:for-each>'||wwv_flow.LF||
'					';
wwv_flow_imp.g_varchar2_table(150) := '				</xsl:for-each>'||wwv_flow.LF||
'								</xsl:for-each>'||wwv_flow.LF||
'							</xsl:for-each>'||wwv_flow.LF||
'							<fo:block/>'||wwv_flow.LF||
'							<xsl:fo';
wwv_flow_imp.g_varchar2_table(151) := 'r-each select="DOCUMENT">'||wwv_flow.LF||
'								<xsl:for-each select="DATA">'||wwv_flow.LF||
'									<xsl:for-each select="ROWSET';
wwv_flow_imp.g_varchar2_table(152) := '2">'||wwv_flow.LF||
'										<xsl:for-each select="ROWSET2_ROW">'||wwv_flow.LF||
'											<xsl:for-each select="CM_ADDRESS1">'||wwv_flow.LF||
'			';
wwv_flow_imp.g_varchar2_table(153) := '									<xsl:variable name="value-of-template_4">'||wwv_flow.LF||
'													<xsl:apply-templates/>'||wwv_flow.LF||
'												<';
wwv_flow_imp.g_varchar2_table(154) := '/xsl:variable>'||wwv_flow.LF||
'												<xsl:choose>'||wwv_flow.LF||
'													<xsl:when test="contains(string($value-of-templ';
wwv_flow_imp.g_varchar2_table(155) := 'ate_4),''&#x200B;'')">'||wwv_flow.LF||
'														<fo:block>'||wwv_flow.LF||
'															<xsl:copy-of select="$value-of-template';
wwv_flow_imp.g_varchar2_table(156) := '_4"/>'||wwv_flow.LF||
'														</fo:block>'||wwv_flow.LF||
'													</xsl:when>'||wwv_flow.LF||
'													<xsl:otherwise>'||wwv_flow.LF||
'														';
wwv_flow_imp.g_varchar2_table(157) := '<fo:inline>'||wwv_flow.LF||
'															<xsl:copy-of select="$value-of-template_4"/>'||wwv_flow.LF||
'														</fo:inline>'||wwv_flow.LF||
'	';
wwv_flow_imp.g_varchar2_table(158) := '												</xsl:otherwise>'||wwv_flow.LF||
'												</xsl:choose>'||wwv_flow.LF||
'											</xsl:for-each>'||wwv_flow.LF||
'										</xsl:fo';
wwv_flow_imp.g_varchar2_table(159) := 'r-each>'||wwv_flow.LF||
'									</xsl:for-each>'||wwv_flow.LF||
'								</xsl:for-each>'||wwv_flow.LF||
'							</xsl:for-each>'||wwv_flow.LF||
'							<fo:block/>'||wwv_flow.LF||
'	';
wwv_flow_imp.g_varchar2_table(160) := '						<xsl:for-each select="DOCUMENT">'||wwv_flow.LF||
'								<xsl:for-each select="DATA">'||wwv_flow.LF||
'									<xsl:for-each s';
wwv_flow_imp.g_varchar2_table(161) := 'elect="ROWSET2">'||wwv_flow.LF||
'										<xsl:for-each select="ROWSET2_ROW">'||wwv_flow.LF||
'											<xsl:for-each select="CM_A';
wwv_flow_imp.g_varchar2_table(162) := 'DDRESS2">'||wwv_flow.LF||
'												<xsl:variable name="value-of-template_5">'||wwv_flow.LF||
'													<xsl:apply-templates/>'||wwv_flow.LF||
'';
wwv_flow_imp.g_varchar2_table(163) := '												</xsl:variable>'||wwv_flow.LF||
'												<xsl:choose>'||wwv_flow.LF||
'													<xsl:when test="contains(string($v';
wwv_flow_imp.g_varchar2_table(164) := 'alue-of-template_5),''&#x200B;'')">'||wwv_flow.LF||
'														<fo:block>'||wwv_flow.LF||
'															<xsl:copy-of select="$valu';
wwv_flow_imp.g_varchar2_table(165) := 'e-of-template_5"/>'||wwv_flow.LF||
'														</fo:block>'||wwv_flow.LF||
'													</xsl:when>'||wwv_flow.LF||
'													<xsl:otherwise>'||wwv_flow.LF||
'	';
wwv_flow_imp.g_varchar2_table(166) := '													<fo:inline>'||wwv_flow.LF||
'															<xsl:copy-of select="$value-of-template_5"/>'||wwv_flow.LF||
'														<';
wwv_flow_imp.g_varchar2_table(167) := '/fo:inline>'||wwv_flow.LF||
'													</xsl:otherwise>'||wwv_flow.LF||
'												</xsl:choose>'||wwv_flow.LF||
'											</xsl:for-each>'||wwv_flow.LF||
'					';
wwv_flow_imp.g_varchar2_table(168) := '					</xsl:for-each>'||wwv_flow.LF||
'									</xsl:for-each>'||wwv_flow.LF||
'								</xsl:for-each>'||wwv_flow.LF||
'							</xsl:for-each>'||wwv_flow.LF||
'							';
wwv_flow_imp.g_varchar2_table(169) := '<fo:block/>'||wwv_flow.LF||
'						</xsl:for-each>'||wwv_flow.LF||
'						<fo:block/>'||wwv_flow.LF||
'						<fo:block>'||wwv_flow.LF||
'							<fo:leader leader-patter';
wwv_flow_imp.g_varchar2_table(170) := 'n="space"/>'||wwv_flow.LF||
'						</fo:block>'||wwv_flow.LF||
'						<fo:block>'||wwv_flow.LF||
'							<fo:leader leader-pattern="space"/>'||wwv_flow.LF||
'						</fo';
wwv_flow_imp.g_varchar2_table(171) := ':block>'||wwv_flow.LF||
'						<fo:inline-container>'||wwv_flow.LF||
'							<fo:block>'||wwv_flow.LF||
'								<xsl:text>&#x200B;</xsl:text>'||wwv_flow.LF||
'							<';
wwv_flow_imp.g_varchar2_table(172) := '/fo:block>'||wwv_flow.LF||
'						</fo:inline-container>'||wwv_flow.LF||
'						<xsl:if test="$XML">'||wwv_flow.LF||
'							<fo:table table-layout="fi';
wwv_flow_imp.g_varchar2_table(173) := 'xed" width="100%" border="solid 1pt gray" border-spacing="2pt">'||wwv_flow.LF||
'								<fo:table-column column-widt';
wwv_flow_imp.g_varchar2_table(174) := 'h="proportional-column-width(1)"/>'||wwv_flow.LF||
'								<fo:table-column column-width="proportional-column-width(';
wwv_flow_imp.g_varchar2_table(175) := '1)"/>'||wwv_flow.LF||
'								<fo:table-column column-width="proportional-column-width(1)"/>'||wwv_flow.LF||
'								<fo:table-colum';
wwv_flow_imp.g_varchar2_table(176) := 'n column-width="proportional-column-width(1)"/>'||wwv_flow.LF||
'								<fo:table-column column-width="proportional-';
wwv_flow_imp.g_varchar2_table(177) := 'column-width(1)"/>'||wwv_flow.LF||
'								<fo:table-column column-width="proportional-column-width(1)"/>'||wwv_flow.LF||
'								<f';
wwv_flow_imp.g_varchar2_table(178) := 'o:table-column column-width="proportional-column-width(1)"/>'||wwv_flow.LF||
'								<xsl:variable name="altova:Curr';
wwv_flow_imp.g_varchar2_table(179) := 'ContextGrid_6" select="."/>'||wwv_flow.LF||
'								<fo:table-header start-indent="0pt">'||wwv_flow.LF||
'									<xsl:variable name';
wwv_flow_imp.g_varchar2_table(180) := '="altova:tablerows">'||wwv_flow.LF||
'										<fo:table-row>'||wwv_flow.LF||
'											<fo:table-cell border="solid 1pt gray" padd';
wwv_flow_imp.g_varchar2_table(181) := 'ing="2pt" display-align="center">'||wwv_flow.LF||
'												<fo:block text-align="left">'||wwv_flow.LF||
'													<fo:inline>'||wwv_flow.LF||
'';
wwv_flow_imp.g_varchar2_table(182) := '														<xsl:text>SR_NO</xsl:text>'||wwv_flow.LF||
'													</fo:inline>'||wwv_flow.LF||
'												</fo:block>'||wwv_flow.LF||
'									';
wwv_flow_imp.g_varchar2_table(183) := '		</fo:table-cell>'||wwv_flow.LF||
'											<fo:table-cell border="solid 1pt gray" padding="2pt" display-align="ce';
wwv_flow_imp.g_varchar2_table(184) := 'nter">'||wwv_flow.LF||
'												<fo:block text-align="left">'||wwv_flow.LF||
'													<fo:inline>'||wwv_flow.LF||
'														<xsl:text>EOD';
wwv_flow_imp.g_varchar2_table(185) := '_QUANTITY</xsl:text>'||wwv_flow.LF||
'													</fo:inline>'||wwv_flow.LF||
'												</fo:block>'||wwv_flow.LF||
'											</fo:table-cell>'||wwv_flow.LF||
'	';
wwv_flow_imp.g_varchar2_table(186) := '										<fo:table-cell border="solid 1pt gray" padding="2pt" display-align="center">'||wwv_flow.LF||
'												<';
wwv_flow_imp.g_varchar2_table(187) := 'fo:block text-align="left">'||wwv_flow.LF||
'													<fo:inline>'||wwv_flow.LF||
'														<xsl:text>PM_UOM</xsl:text>'||wwv_flow.LF||
'					';
wwv_flow_imp.g_varchar2_table(188) := '								</fo:inline>'||wwv_flow.LF||
'												</fo:block>'||wwv_flow.LF||
'											</fo:table-cell>'||wwv_flow.LF||
'											<fo:table-cell b';
wwv_flow_imp.g_varchar2_table(189) := 'order="solid 1pt gray" padding="2pt" display-align="center">'||wwv_flow.LF||
'												<fo:block text-align="left"';
wwv_flow_imp.g_varchar2_table(190) := '>'||wwv_flow.LF||
'													<fo:inline>'||wwv_flow.LF||
'														<xsl:text>PACKING</xsl:text>'||wwv_flow.LF||
'													</fo:inline>'||wwv_flow.LF||
'				';
wwv_flow_imp.g_varchar2_table(191) := '								</fo:block>'||wwv_flow.LF||
'											</fo:table-cell>'||wwv_flow.LF||
'											<fo:table-cell border="solid 1pt gray" pa';
wwv_flow_imp.g_varchar2_table(192) := 'dding="2pt" display-align="center">'||wwv_flow.LF||
'												<fo:block text-align="left">'||wwv_flow.LF||
'													<fo:inline';
wwv_flow_imp.g_varchar2_table(193) := '>'||wwv_flow.LF||
'														<xsl:text>PM_NAME</xsl:text>'||wwv_flow.LF||
'													</fo:inline>'||wwv_flow.LF||
'												</fo:block>'||wwv_flow.LF||
'					';
wwv_flow_imp.g_varchar2_table(194) := '						</fo:table-cell>'||wwv_flow.LF||
'											<fo:table-cell border="solid 1pt gray" padding="2pt" display-align';
wwv_flow_imp.g_varchar2_table(195) := '="center">'||wwv_flow.LF||
'												<fo:block text-align="left">'||wwv_flow.LF||
'													<fo:inline>'||wwv_flow.LF||
'														<xsl:text';
wwv_flow_imp.g_varchar2_table(196) := '>UNIT_FOB</xsl:text>'||wwv_flow.LF||
'													</fo:inline>'||wwv_flow.LF||
'												</fo:block>'||wwv_flow.LF||
'											</fo:table-cell>'||wwv_flow.LF||
'	';
wwv_flow_imp.g_varchar2_table(197) := '										<fo:table-cell border="solid 1pt gray" padding="2pt" display-align="center">'||wwv_flow.LF||
'												<';
wwv_flow_imp.g_varchar2_table(198) := 'fo:block text-align="left">'||wwv_flow.LF||
'													<fo:inline>'||wwv_flow.LF||
'														<xsl:text>TOTAL_FOB</xsl:text>'||wwv_flow.LF||
'		';
wwv_flow_imp.g_varchar2_table(199) := '											</fo:inline>'||wwv_flow.LF||
'												</fo:block>'||wwv_flow.LF||
'											</fo:table-cell>'||wwv_flow.LF||
'										</fo:table-row';
wwv_flow_imp.g_varchar2_table(200) := '>'||wwv_flow.LF||
'									</xsl:variable>'||wwv_flow.LF||
'									<xsl:choose>'||wwv_flow.LF||
'										<xsl:when test="string($altova:tablerows)';
wwv_flow_imp.g_varchar2_table(201) := '">'||wwv_flow.LF||
'											<xsl:copy-of select="$altova:tablerows"/>'||wwv_flow.LF||
'										</xsl:when>'||wwv_flow.LF||
'										<xsl:otherwi';
wwv_flow_imp.g_varchar2_table(202) := 'se>'||wwv_flow.LF||
'											<fo:table-row>'||wwv_flow.LF||
'												<fo:table-cell>'||wwv_flow.LF||
'													<fo:block/>'||wwv_flow.LF||
'												</fo:';
wwv_flow_imp.g_varchar2_table(203) := 'table-cell>'||wwv_flow.LF||
'											</fo:table-row>'||wwv_flow.LF||
'										</xsl:otherwise>'||wwv_flow.LF||
'									</xsl:choose>'||wwv_flow.LF||
'								</f';
wwv_flow_imp.g_varchar2_table(204) := 'o:table-header>'||wwv_flow.LF||
'								<fo:table-body start-indent="0pt">'||wwv_flow.LF||
'									<xsl:variable name="altova:table';
wwv_flow_imp.g_varchar2_table(205) := 'rows">'||wwv_flow.LF||
'										<xsl:for-each select="$XML">'||wwv_flow.LF||
'											<xsl:for-each select="DOCUMENT">'||wwv_flow.LF||
'										';
wwv_flow_imp.g_varchar2_table(206) := '		<xsl:for-each select="DATA">'||wwv_flow.LF||
'													<xsl:for-each select="ROWSET1">'||wwv_flow.LF||
'														<xsl:for-e';
wwv_flow_imp.g_varchar2_table(207) := 'ach select="ROWSET1_ROW">'||wwv_flow.LF||
'															<fo:table-row>'||wwv_flow.LF||
'																<fo:table-cell border="solid';
wwv_flow_imp.g_varchar2_table(208) := ' 1pt gray" padding="2pt" display-align="center">'||wwv_flow.LF||
'																	<fo:block text-align="left">'||wwv_flow.LF||
'					';
wwv_flow_imp.g_varchar2_table(209) := '													<xsl:for-each select="SR_NO">'||wwv_flow.LF||
'																			<xsl:variable name="value-of-template_';
wwv_flow_imp.g_varchar2_table(210) := '7">'||wwv_flow.LF||
'																				<xsl:apply-templates/>'||wwv_flow.LF||
'																			</xsl:variable>'||wwv_flow.LF||
'																		';
wwv_flow_imp.g_varchar2_table(211) := '	<xsl:choose>'||wwv_flow.LF||
'																				<xsl:when test="contains(string($value-of-template_7),''&#x200B;'')"';
wwv_flow_imp.g_varchar2_table(212) := '>'||wwv_flow.LF||
'																					<fo:block>'||wwv_flow.LF||
'																						<xsl:copy-of select="$value-of-template_7"/>';
wwv_flow_imp.g_varchar2_table(213) := ''||wwv_flow.LF||
'																					</fo:block>'||wwv_flow.LF||
'																				</xsl:when>'||wwv_flow.LF||
'																				<xsl:otherwise';
wwv_flow_imp.g_varchar2_table(214) := '>'||wwv_flow.LF||
'																					<fo:inline>'||wwv_flow.LF||
'																						<xsl:copy-of select="$value-of-template_7"/';
wwv_flow_imp.g_varchar2_table(215) := '>'||wwv_flow.LF||
'																					</fo:inline>'||wwv_flow.LF||
'																				</xsl:otherwise>'||wwv_flow.LF||
'																			</xsl:ch';
wwv_flow_imp.g_varchar2_table(216) := 'oose>'||wwv_flow.LF||
'																		</xsl:for-each>'||wwv_flow.LF||
'																	</fo:block>'||wwv_flow.LF||
'																</fo:table-cell';
wwv_flow_imp.g_varchar2_table(217) := '>'||wwv_flow.LF||
'																<fo:table-cell border="solid 1pt gray" padding="2pt" display-align="center">'||wwv_flow.LF||
'					';
wwv_flow_imp.g_varchar2_table(218) := '												<fo:block text-align="left">'||wwv_flow.LF||
'																		<xsl:for-each select="EOD_QUANTITY">'||wwv_flow.LF||
'				';
wwv_flow_imp.g_varchar2_table(219) := '															<xsl:variable name="value-of-template_8">'||wwv_flow.LF||
'																				<xsl:apply-templates/>'||wwv_flow.LF||
'';
wwv_flow_imp.g_varchar2_table(220) := '																			</xsl:variable>'||wwv_flow.LF||
'																			<xsl:choose>'||wwv_flow.LF||
'																				<xsl:when tes';
wwv_flow_imp.g_varchar2_table(221) := 't="contains(string($value-of-template_8),''&#x200B;'')">'||wwv_flow.LF||
'																					<fo:block>'||wwv_flow.LF||
'													';
wwv_flow_imp.g_varchar2_table(222) := '									<xsl:copy-of select="$value-of-template_8"/>'||wwv_flow.LF||
'																					</fo:block>'||wwv_flow.LF||
'													';
wwv_flow_imp.g_varchar2_table(223) := '							</xsl:when>'||wwv_flow.LF||
'																				<xsl:otherwise>'||wwv_flow.LF||
'																					<fo:inline>'||wwv_flow.LF||
'												';
wwv_flow_imp.g_varchar2_table(224) := '										<xsl:copy-of select="$value-of-template_8"/>'||wwv_flow.LF||
'																					</fo:inline>'||wwv_flow.LF||
'											';
wwv_flow_imp.g_varchar2_table(225) := '									</xsl:otherwise>'||wwv_flow.LF||
'																			</xsl:choose>'||wwv_flow.LF||
'																		</xsl:for-each>'||wwv_flow.LF||
'							';
wwv_flow_imp.g_varchar2_table(226) := '										</fo:block>'||wwv_flow.LF||
'																</fo:table-cell>'||wwv_flow.LF||
'																<fo:table-cell border="solid ';
wwv_flow_imp.g_varchar2_table(227) := '1pt gray" padding="2pt" display-align="center">'||wwv_flow.LF||
'																	<fo:block text-align="left">'||wwv_flow.LF||
'						';
wwv_flow_imp.g_varchar2_table(228) := '												<xsl:for-each select="PM_UOM">'||wwv_flow.LF||
'																			<xsl:variable name="value-of-template_';
wwv_flow_imp.g_varchar2_table(229) := '9">'||wwv_flow.LF||
'																				<xsl:apply-templates/>'||wwv_flow.LF||
'																			</xsl:variable>'||wwv_flow.LF||
'																		';
wwv_flow_imp.g_varchar2_table(230) := '	<xsl:choose>'||wwv_flow.LF||
'																				<xsl:when test="contains(string($value-of-template_9),''&#x200B;'')"';
wwv_flow_imp.g_varchar2_table(231) := '>'||wwv_flow.LF||
'																					<fo:block>'||wwv_flow.LF||
'																						<xsl:copy-of select="$value-of-template_9"/>';
wwv_flow_imp.g_varchar2_table(232) := ''||wwv_flow.LF||
'																					</fo:block>'||wwv_flow.LF||
'																				</xsl:when>'||wwv_flow.LF||
'																				<xsl:otherwise';
wwv_flow_imp.g_varchar2_table(233) := '>'||wwv_flow.LF||
'																					<fo:inline>'||wwv_flow.LF||
'																						<xsl:copy-of select="$value-of-template_9"/';
wwv_flow_imp.g_varchar2_table(234) := '>'||wwv_flow.LF||
'																					</fo:inline>'||wwv_flow.LF||
'																				</xsl:otherwise>'||wwv_flow.LF||
'																			</xsl:ch';
wwv_flow_imp.g_varchar2_table(235) := 'oose>'||wwv_flow.LF||
'																		</xsl:for-each>'||wwv_flow.LF||
'																	</fo:block>'||wwv_flow.LF||
'																</fo:table-cell';
wwv_flow_imp.g_varchar2_table(236) := '>'||wwv_flow.LF||
'																<fo:table-cell border="solid 1pt gray" padding="2pt" display-align="center">'||wwv_flow.LF||
'					';
wwv_flow_imp.g_varchar2_table(237) := '												<fo:block text-align="left">'||wwv_flow.LF||
'																		<xsl:for-each select="PACKING">'||wwv_flow.LF||
'									';
wwv_flow_imp.g_varchar2_table(238) := '										<xsl:variable name="value-of-template_10">'||wwv_flow.LF||
'																				<xsl:apply-templates/>'||wwv_flow.LF||
'				';
wwv_flow_imp.g_varchar2_table(239) := '															</xsl:variable>'||wwv_flow.LF||
'																			<xsl:choose>'||wwv_flow.LF||
'																				<xsl:when test="c';
wwv_flow_imp.g_varchar2_table(240) := 'ontains(string($value-of-template_10),''&#x200B;'')">'||wwv_flow.LF||
'																					<fo:block>'||wwv_flow.LF||
'																';
wwv_flow_imp.g_varchar2_table(241) := '						<xsl:copy-of select="$value-of-template_10"/>'||wwv_flow.LF||
'																					</fo:block>'||wwv_flow.LF||
'															';
wwv_flow_imp.g_varchar2_table(242) := '					</xsl:when>'||wwv_flow.LF||
'																				<xsl:otherwise>'||wwv_flow.LF||
'																					<fo:inline>'||wwv_flow.LF||
'														';
wwv_flow_imp.g_varchar2_table(243) := '								<xsl:copy-of select="$value-of-template_10"/>'||wwv_flow.LF||
'																					</fo:inline>'||wwv_flow.LF||
'												';
wwv_flow_imp.g_varchar2_table(244) := '								</xsl:otherwise>'||wwv_flow.LF||
'																			</xsl:choose>'||wwv_flow.LF||
'																		</xsl:for-each>'||wwv_flow.LF||
'								';
wwv_flow_imp.g_varchar2_table(245) := '									</fo:block>'||wwv_flow.LF||
'																</fo:table-cell>'||wwv_flow.LF||
'																<fo:table-cell border="solid 1';
wwv_flow_imp.g_varchar2_table(246) := 'pt gray" padding="2pt" display-align="center">'||wwv_flow.LF||
'																	<fo:block text-align="left">'||wwv_flow.LF||
'							';
wwv_flow_imp.g_varchar2_table(247) := '											<xsl:for-each select="PM_NAME">'||wwv_flow.LF||
'																			<xsl:variable name="value-of-template_';
wwv_flow_imp.g_varchar2_table(248) := '11">'||wwv_flow.LF||
'																				<xsl:apply-templates/>'||wwv_flow.LF||
'																			</xsl:variable>'||wwv_flow.LF||
'																	';
wwv_flow_imp.g_varchar2_table(249) := '		<xsl:choose>'||wwv_flow.LF||
'																				<xsl:when test="contains(string($value-of-template_11),''&#x200B;''';
wwv_flow_imp.g_varchar2_table(250) := ')">'||wwv_flow.LF||
'																					<fo:block>'||wwv_flow.LF||
'																						<xsl:copy-of select="$value-of-template_11';
wwv_flow_imp.g_varchar2_table(251) := '"/>'||wwv_flow.LF||
'																					</fo:block>'||wwv_flow.LF||
'																				</xsl:when>'||wwv_flow.LF||
'																				<xsl:otherw';
wwv_flow_imp.g_varchar2_table(252) := 'ise>'||wwv_flow.LF||
'																					<fo:inline>'||wwv_flow.LF||
'																						<xsl:copy-of select="$value-of-template_';
wwv_flow_imp.g_varchar2_table(253) := '11"/>'||wwv_flow.LF||
'																					</fo:inline>'||wwv_flow.LF||
'																				</xsl:otherwise>'||wwv_flow.LF||
'																			</xs';
wwv_flow_imp.g_varchar2_table(254) := 'l:choose>'||wwv_flow.LF||
'																		</xsl:for-each>'||wwv_flow.LF||
'																	</fo:block>'||wwv_flow.LF||
'																</fo:table-';
wwv_flow_imp.g_varchar2_table(255) := 'cell>'||wwv_flow.LF||
'																<fo:table-cell border="solid 1pt gray" padding="2pt" display-align="center">'||wwv_flow.LF||
'	';
wwv_flow_imp.g_varchar2_table(256) := '																<fo:block text-align="left">'||wwv_flow.LF||
'																		<xsl:for-each select="UNIT_FOB">'||wwv_flow.LF||
'				';
wwv_flow_imp.g_varchar2_table(257) := '															<xsl:variable name="value-of-template_12">'||wwv_flow.LF||
'																				<xsl:apply-templates/>';
wwv_flow_imp.g_varchar2_table(258) := ''||wwv_flow.LF||
'																			</xsl:variable>'||wwv_flow.LF||
'																			<xsl:choose>'||wwv_flow.LF||
'																				<xsl:when te';
wwv_flow_imp.g_varchar2_table(259) := 'st="contains(string($value-of-template_12),''&#x200B;'')">'||wwv_flow.LF||
'																					<fo:block>'||wwv_flow.LF||
'											';
wwv_flow_imp.g_varchar2_table(260) := '											<xsl:copy-of select="$value-of-template_12"/>'||wwv_flow.LF||
'																					</fo:block>'||wwv_flow.LF||
'										';
wwv_flow_imp.g_varchar2_table(261) := '										</xsl:when>'||wwv_flow.LF||
'																				<xsl:otherwise>'||wwv_flow.LF||
'																					<fo:inline>'||wwv_flow.LF||
'									';
wwv_flow_imp.g_varchar2_table(262) := '													<xsl:copy-of select="$value-of-template_12"/>'||wwv_flow.LF||
'																					</fo:inline>'||wwv_flow.LF||
'							';
wwv_flow_imp.g_varchar2_table(263) := '													</xsl:otherwise>'||wwv_flow.LF||
'																			</xsl:choose>'||wwv_flow.LF||
'																		</xsl:for-each>'||wwv_flow.LF||
'			';
wwv_flow_imp.g_varchar2_table(264) := '														</fo:block>'||wwv_flow.LF||
'																</fo:table-cell>'||wwv_flow.LF||
'																<fo:table-cell border="so';
wwv_flow_imp.g_varchar2_table(265) := 'lid 1pt gray" padding="2pt" display-align="center">'||wwv_flow.LF||
'																	<fo:block text-align="left">'||wwv_flow.LF||
'		';
wwv_flow_imp.g_varchar2_table(266) := '																<xsl:for-each select="TOTAL_FOB">'||wwv_flow.LF||
'																			<xsl:variable name="value-of-te';
wwv_flow_imp.g_varchar2_table(267) := 'mplate_13">'||wwv_flow.LF||
'																				<xsl:apply-templates/>'||wwv_flow.LF||
'																			</xsl:variable>'||wwv_flow.LF||
'										';
wwv_flow_imp.g_varchar2_table(268) := '									<xsl:choose>'||wwv_flow.LF||
'																				<xsl:when test="contains(string($value-of-template_13),''&#';
wwv_flow_imp.g_varchar2_table(269) := 'x200B;'')">'||wwv_flow.LF||
'																					<fo:block>'||wwv_flow.LF||
'																						<xsl:copy-of select="$value-of-temp';
wwv_flow_imp.g_varchar2_table(270) := 'late_13"/>'||wwv_flow.LF||
'																					</fo:block>'||wwv_flow.LF||
'																				</xsl:when>'||wwv_flow.LF||
'																				<xsl';
wwv_flow_imp.g_varchar2_table(271) := ':otherwise>'||wwv_flow.LF||
'																					<fo:inline>'||wwv_flow.LF||
'																						<xsl:copy-of select="$value-of-te';
wwv_flow_imp.g_varchar2_table(272) := 'mplate_13"/>'||wwv_flow.LF||
'																					</fo:inline>'||wwv_flow.LF||
'																				</xsl:otherwise>'||wwv_flow.LF||
'																';
wwv_flow_imp.g_varchar2_table(273) := '			</xsl:choose>'||wwv_flow.LF||
'																		</xsl:for-each>'||wwv_flow.LF||
'																	</fo:block>'||wwv_flow.LF||
'																</fo';
wwv_flow_imp.g_varchar2_table(274) := ':table-cell>'||wwv_flow.LF||
'															</fo:table-row>'||wwv_flow.LF||
'														</xsl:for-each>'||wwv_flow.LF||
'													</xsl:for-eac';
wwv_flow_imp.g_varchar2_table(275) := 'h>'||wwv_flow.LF||
'												</xsl:for-each>'||wwv_flow.LF||
'											</xsl:for-each>'||wwv_flow.LF||
'										</xsl:for-each>'||wwv_flow.LF||
'									</xsl:v';
wwv_flow_imp.g_varchar2_table(276) := 'ariable>'||wwv_flow.LF||
'									<xsl:choose>'||wwv_flow.LF||
'										<xsl:when test="string($altova:tablerows)">'||wwv_flow.LF||
'											<xsl';
wwv_flow_imp.g_varchar2_table(277) := ':copy-of select="$altova:tablerows"/>'||wwv_flow.LF||
'										</xsl:when>'||wwv_flow.LF||
'										<xsl:otherwise>'||wwv_flow.LF||
'											<fo';
wwv_flow_imp.g_varchar2_table(278) := ':table-row>'||wwv_flow.LF||
'												<fo:table-cell>'||wwv_flow.LF||
'													<fo:block/>'||wwv_flow.LF||
'												</fo:table-cell>'||wwv_flow.LF||
'						';
wwv_flow_imp.g_varchar2_table(279) := '					</fo:table-row>'||wwv_flow.LF||
'										</xsl:otherwise>'||wwv_flow.LF||
'									</xsl:choose>'||wwv_flow.LF||
'								</fo:table-body>'||wwv_flow.LF||
'				';
wwv_flow_imp.g_varchar2_table(280) := '			</fo:table>'||wwv_flow.LF||
'						</xsl:if>'||wwv_flow.LF||
'						<fo:block>'||wwv_flow.LF||
'							<fo:leader leader-pattern="space"/>'||wwv_flow.LF||
'						</f';
wwv_flow_imp.g_varchar2_table(281) := 'o:block>'||wwv_flow.LF||
'						<fo:block>'||wwv_flow.LF||
'							<fo:leader leader-pattern="space"/>'||wwv_flow.LF||
'						</fo:block>'||wwv_flow.LF||
'					</fo:blo';
wwv_flow_imp.g_varchar2_table(282) := 'ck>'||wwv_flow.LF||
'					<fo:block id="SV_RefID_PageTotal"/>'||wwv_flow.LF||
'				</fo:flow>'||wwv_flow.LF||
'			</fo:page-sequence>'||wwv_flow.LF||
'		</fo:root>'||wwv_flow.LF||
'	</x';
wwv_flow_imp.g_varchar2_table(283) := 'sl:template>'||wwv_flow.LF||
'	<xsl:template name="altova:double-backslash">'||wwv_flow.LF||
'		<xsl:param name="text"/>'||wwv_flow.LF||
'		<xsl:param ';
wwv_flow_imp.g_varchar2_table(284) := 'name="text-length"/>'||wwv_flow.LF||
'		<xsl:variable name="text-after-bs" select="substring-after($text, ''\'')"/>'||wwv_flow.LF||
'		<';
wwv_flow_imp.g_varchar2_table(285) := 'xsl:variable name="text-after-bs-length" select="string-length($text-after-bs)"/>'||wwv_flow.LF||
'		<xsl:choose>'||wwv_flow.LF||
'			';
wwv_flow_imp.g_varchar2_table(286) := '<xsl:when test="$text-after-bs-length = 0">'||wwv_flow.LF||
'				<xsl:choose>'||wwv_flow.LF||
'					<xsl:when test="substring($text, $';
wwv_flow_imp.g_varchar2_table(287) := 'text-length) = ''\''">'||wwv_flow.LF||
'						<xsl:value-of select="concat(substring($text,1,$text-length - 1), ''\\'')"/';
wwv_flow_imp.g_varchar2_table(288) := '>'||wwv_flow.LF||
'					</xsl:when>'||wwv_flow.LF||
'					<xsl:otherwise>'||wwv_flow.LF||
'						<xsl:value-of select="$text"/>'||wwv_flow.LF||
'					</xsl:otherwise>'||wwv_flow.LF||
'	';
wwv_flow_imp.g_varchar2_table(289) := '			</xsl:choose>'||wwv_flow.LF||
'			</xsl:when>'||wwv_flow.LF||
'			<xsl:otherwise>'||wwv_flow.LF||
'				<xsl:value-of select="concat(substring($text,';
wwv_flow_imp.g_varchar2_table(290) := '1,$text-length - $text-after-bs-length - 1), ''\\'')"/>'||wwv_flow.LF||
'				<xsl:call-template name="altova:double-bac';
wwv_flow_imp.g_varchar2_table(291) := 'kslash">'||wwv_flow.LF||
'					<xsl:with-param name="text" select="$text-after-bs"/>'||wwv_flow.LF||
'					<xsl:with-param name="text-';
wwv_flow_imp.g_varchar2_table(292) := 'length" select="$text-after-bs-length"/>'||wwv_flow.LF||
'				</xsl:call-template>'||wwv_flow.LF||
'			</xsl:otherwise>'||wwv_flow.LF||
'		</xsl:choose';
wwv_flow_imp.g_varchar2_table(293) := '>'||wwv_flow.LF||
'	</xsl:template>'||wwv_flow.LF||
'	<xsl:template name="altova:MakeValueAbsoluteIfPixels">'||wwv_flow.LF||
'		<xsl:param name="sValue';
wwv_flow_imp.g_varchar2_table(294) := '"/>'||wwv_flow.LF||
'		<xsl:variable name="sBeforePx" select="substring-before($sValue, ''px'')"/>'||wwv_flow.LF||
'		<xsl:choose>'||wwv_flow.LF||
'			<x';
wwv_flow_imp.g_varchar2_table(295) := 'sl:when test="$sBeforePx">'||wwv_flow.LF||
'				<xsl:variable name="nLengthOfInteger">'||wwv_flow.LF||
'					<xsl:call-template name="';
wwv_flow_imp.g_varchar2_table(296) := 'altova:GetCharCountOfIntegerAtEndOfString">'||wwv_flow.LF||
'						<xsl:with-param name="sText" select="$sBeforePx"/>';
wwv_flow_imp.g_varchar2_table(297) := ''||wwv_flow.LF||
'					</xsl:call-template>'||wwv_flow.LF||
'				</xsl:variable>'||wwv_flow.LF||
'				<xsl:variable name="nPosOfInteger" select="string';
wwv_flow_imp.g_varchar2_table(298) := '-length($sBeforePx) - $nLengthOfInteger + 1"/>'||wwv_flow.LF||
'				<xsl:variable name="nValuePx" select="substring($';
wwv_flow_imp.g_varchar2_table(299) := 'sBeforePx, $nPosOfInteger)"/>'||wwv_flow.LF||
'				<xsl:variable name="nValueIn" select="number($nValuePx) div number';
wwv_flow_imp.g_varchar2_table(300) := '($altova:nPxPerIn)"/>'||wwv_flow.LF||
'				<xsl:variable name="nLengthBeforeInteger" select="string-length($sBeforePx';
wwv_flow_imp.g_varchar2_table(301) := ') - $nLengthOfInteger"/>'||wwv_flow.LF||
'				<xsl:variable name="sRest">'||wwv_flow.LF||
'					<xsl:call-template name="altova:MakeVa';
wwv_flow_imp.g_varchar2_table(302) := 'lueAbsoluteIfPixels">'||wwv_flow.LF||
'						<xsl:with-param name="sValue" select="substring-after($sValue, ''px'')"/>'||wwv_flow.LF||
'';
wwv_flow_imp.g_varchar2_table(303) := '					</xsl:call-template>'||wwv_flow.LF||
'				</xsl:variable>'||wwv_flow.LF||
'				<xsl:value-of select="concat(substring($sBeforePx,';
wwv_flow_imp.g_varchar2_table(304) := ' 1, $nLengthBeforeInteger), string($nValueIn), ''in'', $sRest)"/>'||wwv_flow.LF||
'			</xsl:when>'||wwv_flow.LF||
'			<xsl:otherwise>'||wwv_flow.LF||
'		';
wwv_flow_imp.g_varchar2_table(305) := '		<xsl:value-of select="$sValue"/>'||wwv_flow.LF||
'			</xsl:otherwise>'||wwv_flow.LF||
'		</xsl:choose>'||wwv_flow.LF||
'	</xsl:template>'||wwv_flow.LF||
'	<xsl:templa';
wwv_flow_imp.g_varchar2_table(306) := 'te name="altova:GetCharCountOfIntegerAtEndOfString">'||wwv_flow.LF||
'		<xsl:param name="sText"/>'||wwv_flow.LF||
'		<xsl:variable nam';
wwv_flow_imp.g_varchar2_table(307) := 'e="sLen" select="string-length($sText)"/>'||wwv_flow.LF||
'		<xsl:variable name="cLast" select="substring($sText, $sL';
wwv_flow_imp.g_varchar2_table(308) := 'en)"/>'||wwv_flow.LF||
'		<xsl:choose>'||wwv_flow.LF||
'			<xsl:when test="number($cLast) &gt;= 0 and number($cLast) &lt;= 9">'||wwv_flow.LF||
'				<xs';
wwv_flow_imp.g_varchar2_table(309) := 'l:variable name="nResultOfRest">'||wwv_flow.LF||
'					<xsl:call-template name="altova:GetCharCountOfIntegerAtEndOfSt';
wwv_flow_imp.g_varchar2_table(310) := 'ring">'||wwv_flow.LF||
'						<xsl:with-param name="sText" select="substring($sText, 1, $sLen - 1)"/>'||wwv_flow.LF||
'					</xsl:call';
wwv_flow_imp.g_varchar2_table(311) := '-template>'||wwv_flow.LF||
'				</xsl:variable>'||wwv_flow.LF||
'				<xsl:value-of select="$nResultOfRest + 1"/>'||wwv_flow.LF||
'			</xsl:when>'||wwv_flow.LF||
'			<xs';
wwv_flow_imp.g_varchar2_table(312) := 'l:otherwise>'||wwv_flow.LF||
'				<xsl:text>0</xsl:text>'||wwv_flow.LF||
'			</xsl:otherwise>'||wwv_flow.LF||
'		</xsl:choose>'||wwv_flow.LF||
'	</xsl:template>'||wwv_flow.LF||
'</xsl:s';
wwv_flow_imp.g_varchar2_table(313) := 'tylesheet>'||wwv_flow.LF||
'';
wwv_flow_imp.component_end;
end;
/
begin
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.15'
,p_default_workspace_id=>7965342552622829
,p_default_application_id=>200
,p_default_id_offset=>32162224829641601
,p_default_owner=>'SAARTHIDEV'
);
wwv_flow_imp_shared.create_report_layout(
 p_id=>wwv_flow_imp.id(163749126739458001)
,p_report_layout_name=>'enq'
,p_static_id=>'ENQ_243799970126093727'
,p_report_layout_type=>'XSL_FILE'
,p_varchar2_table=>wwv_flow_imp.g_varchar2_table
,p_version_scn=>350683261
);
wwv_flow_imp.component_end;
end;
/
