prompt --application/shared_components/reports/report_layouts/test
begin
--   Manifest
--     REPORT LAYOUT: test
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.15'
,p_default_workspace_id=>7965342552622829
,p_default_application_id=>200
,p_default_id_offset=>32162224829641601
,p_default_owner=>'SAARTHIDEV'
);
wwv_flow_imp.g_varchar2_table := wwv_flow_imp.empty_varchar2_table;
wwv_flow_imp.g_varchar2_table(1) := '<?xml version="1.0" encoding="UTF-8"?>'||wwv_flow.LF||
'<!--Designed and generated by Altova StyleVision Enterprise E';
wwv_flow_imp.g_varchar2_table(2) := 'dition 2017 sp2 - see http://www.altova.com/stylevision for more information.-->'||wwv_flow.LF||
'<xsl:stylesheet ver';
wwv_flow_imp.g_varchar2_table(3) := 'sion="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:altova="http://www.altova.com" xml';
wwv_flow_imp.g_varchar2_table(4) := 'ns:altova-xfi="http://www.altova.com/xslt-extensions/xbrl" xmlns:altovaext="http://www.altova.com/xs';
wwv_flow_imp.g_varchar2_table(5) := 'lt-extensions" xmlns:array="http://www.w3.org/2005/xpath-functions/array" xmlns:clitype="clitype" xm';
wwv_flow_imp.g_varchar2_table(6) := 'lns:fn="http://www.w3.org/2005/xpath-functions" xmlns:iso4217="http://www.xbrl.org/2003/iso4217" xml';
wwv_flow_imp.g_varchar2_table(7) := 'ns:ix="http://www.xbrl.org/2008/inlineXBRL" xmlns:java="java" xmlns:link="http://www.xbrl.org/2003/l';
wwv_flow_imp.g_varchar2_table(8) := 'inkbase" xmlns:map="http://www.w3.org/2005/xpath-functions/map" xmlns:math="http://www.w3.org/2005/x';
wwv_flow_imp.g_varchar2_table(9) := 'path-functions/math" xmlns:sps="http://www.altova.com/StyleVision/user-xpath-functions" xmlns:xbrldi';
wwv_flow_imp.g_varchar2_table(10) := '="http://xbrl.org/2006/xbrldi" xmlns:xbrli="http://www.xbrl.org/2003/instance" xmlns:xff="http://www';
wwv_flow_imp.g_varchar2_table(11) := '.xbrl.org/2010/function/formula" xmlns:xfi="http://www.xbrl.org/2008/function/instance" xmlns:xlink=';
wwv_flow_imp.g_varchar2_table(12) := '"http://www.w3.org/1999/xlink" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.';
wwv_flow_imp.g_varchar2_table(13) := 'org/2001/XMLSchema-instance" xmlns:fo="http://www.w3.org/1999/XSL/Format" xmlns:svg="http://www.w3.o';
wwv_flow_imp.g_varchar2_table(14) := 'rg/2000/svg" exclude-result-prefixes="altova altova-xfi altovaext array clitype fn iso4217 ix java l';
wwv_flow_imp.g_varchar2_table(15) := 'ink map math sps xbrldi xbrli xff xfi xlink xs xsi">'||wwv_flow.LF||
'	<xsl:output version="1.0" method="xml" encodin';
wwv_flow_imp.g_varchar2_table(16) := 'g="UTF-8" indent="no"/>'||wwv_flow.LF||
'	<xsl:param name="SV_OutputFormat" select="''PDF''"/>'||wwv_flow.LF||
'	<xsl:variable name="fo:';
wwv_flow_imp.g_varchar2_table(17) := 'layout-master-set">'||wwv_flow.LF||
'		<fo:layout-master-set>'||wwv_flow.LF||
'			<fo:simple-page-master master-name="page-master-0-ev';
wwv_flow_imp.g_varchar2_table(18) := 'en" margin-left="1.000in" margin-right="1.000in" page-height="11.693in" page-width="8.268in" margin-';
wwv_flow_imp.g_varchar2_table(19) := 'top="0.492in" margin-bottom="0.492in">'||wwv_flow.LF||
'				<fo:region-body margin-top="0.51in" margin-bottom="0.51in';
wwv_flow_imp.g_varchar2_table(20) := '" column-count="1" column-gap="0.50in"/>'||wwv_flow.LF||
'				<fo:region-before region-name="even-page-header" overfl';
wwv_flow_imp.g_varchar2_table(21) := 'ow="hidden" extent="0.51in"/>'||wwv_flow.LF||
'				<fo:region-after region-name="even-page-footer" overflow="hidden" ';
wwv_flow_imp.g_varchar2_table(22) := 'extent="0.51in"/>'||wwv_flow.LF||
'			</fo:simple-page-master>'||wwv_flow.LF||
'			<fo:simple-page-master master-name="page-master-0-o';
wwv_flow_imp.g_varchar2_table(23) := 'dd" margin-left="1.000in" margin-right="1.000in" page-height="11.693in" page-width="8.268in" margin-';
wwv_flow_imp.g_varchar2_table(24) := 'top="0.492in" margin-bottom="0.492in">'||wwv_flow.LF||
'				<fo:region-body margin-top="0.51in" margin-bottom="0.51in';
wwv_flow_imp.g_varchar2_table(25) := '" column-count="1" column-gap="0.50in"/>'||wwv_flow.LF||
'				<fo:region-before region-name="odd-page-header" overflo';
wwv_flow_imp.g_varchar2_table(26) := 'w="hidden" extent="0.51in"/>'||wwv_flow.LF||
'				<fo:region-after region-name="odd-page-footer" overflow="hidden" ex';
wwv_flow_imp.g_varchar2_table(27) := 'tent="0.51in"/>'||wwv_flow.LF||
'			</fo:simple-page-master>'||wwv_flow.LF||
'			<fo:page-sequence-master master-name="page-master-0">';
wwv_flow_imp.g_varchar2_table(28) := ''||wwv_flow.LF||
'				<fo:repeatable-page-master-alternatives>'||wwv_flow.LF||
'					<fo:conditional-page-master-reference master-refe';
wwv_flow_imp.g_varchar2_table(29) := 'rence="page-master-0-even" odd-or-even="even"/>'||wwv_flow.LF||
'					<fo:conditional-page-master-reference master-re';
wwv_flow_imp.g_varchar2_table(30) := 'ference="page-master-0-odd" odd-or-even="odd"/>'||wwv_flow.LF||
'				</fo:repeatable-page-master-alternatives>'||wwv_flow.LF||
'			</f';
wwv_flow_imp.g_varchar2_table(31) := 'o:page-sequence-master>'||wwv_flow.LF||
'		</fo:layout-master-set>'||wwv_flow.LF||
'	</xsl:variable>'||wwv_flow.LF||
'	<xsl:variable name="altova:nPxPe';
wwv_flow_imp.g_varchar2_table(32) := 'rIn" select="96"/>'||wwv_flow.LF||
'	<xsl:template match="/">'||wwv_flow.LF||
'		<fo:root>'||wwv_flow.LF||
'			<xsl:copy-of select="$fo:layout-master-s';
wwv_flow_imp.g_varchar2_table(33) := 'et"/>'||wwv_flow.LF||
'			<fo:declarations>'||wwv_flow.LF||
'				<x:xmpmeta xmlns:x="adobe:ns:meta/">'||wwv_flow.LF||
'					<rdf:RDF xmlns:rdf="http://';
wwv_flow_imp.g_varchar2_table(34) := 'www.w3.org/1999/02/22-rdf-syntax-ns#">'||wwv_flow.LF||
'						<rdf:Description rdf:about="" xmlns:xmp="http://ns.adob';
wwv_flow_imp.g_varchar2_table(35) := 'e.com/xap/1.0/">'||wwv_flow.LF||
'							<xmp:CreatorTool>Altova StyleVision Enterprise Edition 2017 sp2 (http://www.';
wwv_flow_imp.g_varchar2_table(36) := 'altova.com)</xmp:CreatorTool>'||wwv_flow.LF||
'						</rdf:Description>'||wwv_flow.LF||
'					</rdf:RDF>'||wwv_flow.LF||
'				</x:xmpmeta>'||wwv_flow.LF||
'			</fo:decl';
wwv_flow_imp.g_varchar2_table(37) := 'arations>'||wwv_flow.LF||
'			<fo:page-sequence force-page-count="no-force" master-reference="page-master-0" initial-';
wwv_flow_imp.g_varchar2_table(38) := 'page-number="auto" format="1">'||wwv_flow.LF||
'				<fo:static-content flow-name="odd-page-header">'||wwv_flow.LF||
'					<fo:block-co';
wwv_flow_imp.g_varchar2_table(39) := 'ntainer overflow="hidden" display-align="before">'||wwv_flow.LF||
'						<fo:block>'||wwv_flow.LF||
'							<fo:inline-container>'||wwv_flow.LF||
'				';
wwv_flow_imp.g_varchar2_table(40) := '				<fo:block>'||wwv_flow.LF||
'									<xsl:text>&#x200B;</xsl:text>'||wwv_flow.LF||
'								</fo:block>'||wwv_flow.LF||
'							</fo:inline-contain';
wwv_flow_imp.g_varchar2_table(41) := 'er>'||wwv_flow.LF||
'							<fo:table width="100%" table-layout="fixed" border-spacing="2pt">'||wwv_flow.LF||
'								<fo:table-colum';
wwv_flow_imp.g_varchar2_table(42) := 'n column-width="90%"/>'||wwv_flow.LF||
'								<xsl:variable name="altova:CurrContextGrid_1" select="."/>'||wwv_flow.LF||
'								<f';
wwv_flow_imp.g_varchar2_table(43) := 'o:table-body start-indent="0pt">'||wwv_flow.LF||
'									<xsl:variable name="altova:tablerows">'||wwv_flow.LF||
'										<fo:table';
wwv_flow_imp.g_varchar2_table(44) := '-row>'||wwv_flow.LF||
'											<fo:table-cell font-size="10pt" padding="0" display-align="center">'||wwv_flow.LF||
'												<fo';
wwv_flow_imp.g_varchar2_table(45) := ':block text-align="left">'||wwv_flow.LF||
'													<fo:external-graphic>'||wwv_flow.LF||
'														<xsl:attribute name="src"';
wwv_flow_imp.g_varchar2_table(46) := '>'||wwv_flow.LF||
'															<xsl:text>url(</xsl:text>'||wwv_flow.LF||
'															<xsl:call-template name="altova:double-bac';
wwv_flow_imp.g_varchar2_table(47) := 'kslash">'||wwv_flow.LF||
'																<xsl:with-param name="text">'||wwv_flow.LF||
'																	<xsl:value-of select="string(';
wwv_flow_imp.g_varchar2_table(48) := '&apos;file:///F:/apex_5.0.3/apex/images/letter_grid.gif&apos;)"/>'||wwv_flow.LF||
'																</xsl:with-param>'||wwv_flow.LF||
'';
wwv_flow_imp.g_varchar2_table(49) := '																<xsl:with-param name="text-length">'||wwv_flow.LF||
'																	<xsl:value-of select="string-le';
wwv_flow_imp.g_varchar2_table(50) := 'ngth(string(&apos;file:///F:/apex_5.0.3/apex/images/letter_grid.gif&apos;))"/>'||wwv_flow.LF||
'																</xsl';
wwv_flow_imp.g_varchar2_table(51) := ':with-param>'||wwv_flow.LF||
'															</xsl:call-template>'||wwv_flow.LF||
'															<xsl:text>)</xsl:text>'||wwv_flow.LF||
'													';
wwv_flow_imp.g_varchar2_table(52) := '	</xsl:attribute>'||wwv_flow.LF||
'													</fo:external-graphic>'||wwv_flow.LF||
'													<fo:inline>'||wwv_flow.LF||
'														<xsl:te';
wwv_flow_imp.g_varchar2_table(53) := 'xt>&#x200B;</xsl:text>'||wwv_flow.LF||
'													</fo:inline>'||wwv_flow.LF||
'												</fo:block>'||wwv_flow.LF||
'											</fo:table-cell>';
wwv_flow_imp.g_varchar2_table(54) := ''||wwv_flow.LF||
'										</fo:table-row>'||wwv_flow.LF||
'										<fo:table-row>'||wwv_flow.LF||
'											<fo:table-cell padding="0" display-al';
wwv_flow_imp.g_varchar2_table(55) := 'ign="center">'||wwv_flow.LF||
'												<fo:block text-align="left">'||wwv_flow.LF||
'													<fo:block text-align="center">'||wwv_flow.LF||
'	';
wwv_flow_imp.g_varchar2_table(56) := '													<fo:leader leader-pattern="rule" rule-thickness="1" leader-length="100%" color="black"/';
wwv_flow_imp.g_varchar2_table(57) := '>'||wwv_flow.LF||
'													</fo:block>'||wwv_flow.LF||
'												</fo:block>'||wwv_flow.LF||
'											</fo:table-cell>'||wwv_flow.LF||
'										</fo:table-';
wwv_flow_imp.g_varchar2_table(58) := 'row>'||wwv_flow.LF||
'									</xsl:variable>'||wwv_flow.LF||
'									<xsl:choose>'||wwv_flow.LF||
'										<xsl:when test="string($altova:tablero';
wwv_flow_imp.g_varchar2_table(59) := 'ws)">'||wwv_flow.LF||
'											<xsl:copy-of select="$altova:tablerows"/>'||wwv_flow.LF||
'										</xsl:when>'||wwv_flow.LF||
'										<xsl:othe';
wwv_flow_imp.g_varchar2_table(60) := 'rwise>'||wwv_flow.LF||
'											<fo:table-row>'||wwv_flow.LF||
'												<fo:table-cell>'||wwv_flow.LF||
'													<fo:block/>'||wwv_flow.LF||
'												</';
wwv_flow_imp.g_varchar2_table(61) := 'fo:table-cell>'||wwv_flow.LF||
'											</fo:table-row>'||wwv_flow.LF||
'										</xsl:otherwise>'||wwv_flow.LF||
'									</xsl:choose>'||wwv_flow.LF||
'								';
wwv_flow_imp.g_varchar2_table(62) := '</fo:table-body>'||wwv_flow.LF||
'							</fo:table>'||wwv_flow.LF||
'						</fo:block>'||wwv_flow.LF||
'					</fo:block-container>'||wwv_flow.LF||
'				</fo:static-con';
wwv_flow_imp.g_varchar2_table(63) := 'tent>'||wwv_flow.LF||
'				<fo:static-content flow-name="even-page-header">'||wwv_flow.LF||
'					<fo:block-container overflow="hidden';
wwv_flow_imp.g_varchar2_table(64) := '" display-align="before">'||wwv_flow.LF||
'						<fo:block>'||wwv_flow.LF||
'							<fo:inline-container>'||wwv_flow.LF||
'								<fo:block>'||wwv_flow.LF||
'									';
wwv_flow_imp.g_varchar2_table(65) := '<xsl:text>&#x200B;</xsl:text>'||wwv_flow.LF||
'								</fo:block>'||wwv_flow.LF||
'							</fo:inline-container>'||wwv_flow.LF||
'							<fo:table wid';
wwv_flow_imp.g_varchar2_table(66) := 'th="100%" table-layout="fixed" border-spacing="2pt">'||wwv_flow.LF||
'								<fo:table-column column-width="90%"/>'||wwv_flow.LF||
'	';
wwv_flow_imp.g_varchar2_table(67) := '							<xsl:variable name="altova:CurrContextGrid_1" select="."/>'||wwv_flow.LF||
'								<fo:table-body start-inden';
wwv_flow_imp.g_varchar2_table(68) := 't="0pt">'||wwv_flow.LF||
'									<xsl:variable name="altova:tablerows">'||wwv_flow.LF||
'										<fo:table-row>'||wwv_flow.LF||
'											<fo:tab';
wwv_flow_imp.g_varchar2_table(69) := 'le-cell font-size="10pt" padding="0" display-align="center">'||wwv_flow.LF||
'												<fo:block text-align="left"';
wwv_flow_imp.g_varchar2_table(70) := '>'||wwv_flow.LF||
'													<fo:external-graphic>'||wwv_flow.LF||
'														<xsl:attribute name="src">'||wwv_flow.LF||
'															<xsl:te';
wwv_flow_imp.g_varchar2_table(71) := 'xt>url(</xsl:text>'||wwv_flow.LF||
'															<xsl:call-template name="altova:double-backslash">'||wwv_flow.LF||
'															';
wwv_flow_imp.g_varchar2_table(72) := '	<xsl:with-param name="text">'||wwv_flow.LF||
'																	<xsl:value-of select="string(&apos;file:///F:/apex_5.';
wwv_flow_imp.g_varchar2_table(73) := '0.3/apex/images/letter_grid.gif&apos;)"/>'||wwv_flow.LF||
'																</xsl:with-param>'||wwv_flow.LF||
'																<xsl:wit';
wwv_flow_imp.g_varchar2_table(74) := 'h-param name="text-length">'||wwv_flow.LF||
'																	<xsl:value-of select="string-length(string(&apos;file:/';
wwv_flow_imp.g_varchar2_table(75) := '//F:/apex_5.0.3/apex/images/letter_grid.gif&apos;))"/>'||wwv_flow.LF||
'																</xsl:with-param>'||wwv_flow.LF||
'											';
wwv_flow_imp.g_varchar2_table(76) := '				</xsl:call-template>'||wwv_flow.LF||
'															<xsl:text>)</xsl:text>'||wwv_flow.LF||
'														</xsl:attribute>'||wwv_flow.LF||
'						';
wwv_flow_imp.g_varchar2_table(77) := '							</fo:external-graphic>'||wwv_flow.LF||
'													<fo:inline>'||wwv_flow.LF||
'														<xsl:text>&#x200B;</xsl:text>'||wwv_flow.LF||
'	';
wwv_flow_imp.g_varchar2_table(78) := '												</fo:inline>'||wwv_flow.LF||
'												</fo:block>'||wwv_flow.LF||
'											</fo:table-cell>'||wwv_flow.LF||
'										</fo:table-ro';
wwv_flow_imp.g_varchar2_table(79) := 'w>'||wwv_flow.LF||
'										<fo:table-row>'||wwv_flow.LF||
'											<fo:table-cell padding="0" display-align="center">'||wwv_flow.LF||
'										';
wwv_flow_imp.g_varchar2_table(80) := '		<fo:block text-align="left">'||wwv_flow.LF||
'													<fo:block text-align="center">'||wwv_flow.LF||
'														<fo:leader ';
wwv_flow_imp.g_varchar2_table(81) := 'leader-pattern="rule" rule-thickness="1" leader-length="100%" color="black"/>'||wwv_flow.LF||
'													</fo:bloc';
wwv_flow_imp.g_varchar2_table(82) := 'k>'||wwv_flow.LF||
'												</fo:block>'||wwv_flow.LF||
'											</fo:table-cell>'||wwv_flow.LF||
'										</fo:table-row>'||wwv_flow.LF||
'									</xsl:vari';
wwv_flow_imp.g_varchar2_table(83) := 'able>'||wwv_flow.LF||
'									<xsl:choose>'||wwv_flow.LF||
'										<xsl:when test="string($altova:tablerows)">'||wwv_flow.LF||
'											<xsl:co';
wwv_flow_imp.g_varchar2_table(84) := 'py-of select="$altova:tablerows"/>'||wwv_flow.LF||
'										</xsl:when>'||wwv_flow.LF||
'										<xsl:otherwise>'||wwv_flow.LF||
'											<fo:ta';
wwv_flow_imp.g_varchar2_table(85) := 'ble-row>'||wwv_flow.LF||
'												<fo:table-cell>'||wwv_flow.LF||
'													<fo:block/>'||wwv_flow.LF||
'												</fo:table-cell>'||wwv_flow.LF||
'									';
wwv_flow_imp.g_varchar2_table(86) := '		</fo:table-row>'||wwv_flow.LF||
'										</xsl:otherwise>'||wwv_flow.LF||
'									</xsl:choose>'||wwv_flow.LF||
'								</fo:table-body>'||wwv_flow.LF||
'							';
wwv_flow_imp.g_varchar2_table(87) := '</fo:table>'||wwv_flow.LF||
'						</fo:block>'||wwv_flow.LF||
'					</fo:block-container>'||wwv_flow.LF||
'				</fo:static-content>'||wwv_flow.LF||
'				<fo:static-con';
wwv_flow_imp.g_varchar2_table(88) := 'tent flow-name="odd-page-footer">'||wwv_flow.LF||
'					<fo:block-container height="0.51in" overflow="hidden" display';
wwv_flow_imp.g_varchar2_table(89) := '-align="after">'||wwv_flow.LF||
'						<fo:block>'||wwv_flow.LF||
'							<fo:inline-container>'||wwv_flow.LF||
'								<fo:block>'||wwv_flow.LF||
'									<xsl:text>';
wwv_flow_imp.g_varchar2_table(90) := '&#x200B;</xsl:text>'||wwv_flow.LF||
'								</fo:block>'||wwv_flow.LF||
'							</fo:inline-container>'||wwv_flow.LF||
'							<fo:table width="100%" ';
wwv_flow_imp.g_varchar2_table(91) := 'table-layout="fixed" border-spacing="2pt">'||wwv_flow.LF||
'								<fo:table-column column-width="90%"/>'||wwv_flow.LF||
'								<fo';
wwv_flow_imp.g_varchar2_table(92) := ':table-column column-width="10%"/>'||wwv_flow.LF||
'								<xsl:variable name="altova:CurrContextGrid_2" select="."/';
wwv_flow_imp.g_varchar2_table(93) := '>'||wwv_flow.LF||
'								<fo:table-body start-indent="0pt">'||wwv_flow.LF||
'									<xsl:variable name="altova:tablerows">'||wwv_flow.LF||
'							';
wwv_flow_imp.g_varchar2_table(94) := '			<fo:table-row>'||wwv_flow.LF||
'											<fo:table-cell number-columns-spanned="2" padding="0" display-align="ce';
wwv_flow_imp.g_varchar2_table(95) := 'nter">'||wwv_flow.LF||
'												<fo:block text-align="left">'||wwv_flow.LF||
'													<fo:block text-align="center">'||wwv_flow.LF||
'								';
wwv_flow_imp.g_varchar2_table(96) := '						<fo:leader leader-pattern="rule" rule-thickness="1" leader-length="100%" color="black"/>'||wwv_flow.LF||
'					';
wwv_flow_imp.g_varchar2_table(97) := '								</fo:block>'||wwv_flow.LF||
'												</fo:block>'||wwv_flow.LF||
'											</fo:table-cell>'||wwv_flow.LF||
'										</fo:table-row>'||wwv_flow.LF||
'		';
wwv_flow_imp.g_varchar2_table(98) := '								<fo:table-row>'||wwv_flow.LF||
'											<fo:table-cell font-size="10pt" padding="0" display-align="center"';
wwv_flow_imp.g_varchar2_table(99) := '>'||wwv_flow.LF||
'												<fo:block text-align="center">'||wwv_flow.LF||
'													<fo:block>'||wwv_flow.LF||
'														<fo:leader leader';
wwv_flow_imp.g_varchar2_table(100) := '-pattern="space"/>'||wwv_flow.LF||
'													</fo:block>'||wwv_flow.LF||
'													<fo:inline-container>'||wwv_flow.LF||
'														<fo:blo';
wwv_flow_imp.g_varchar2_table(101) := 'ck>'||wwv_flow.LF||
'															<xsl:text>&#x200B;</xsl:text>'||wwv_flow.LF||
'														</fo:block>'||wwv_flow.LF||
'													</fo:inline-';
wwv_flow_imp.g_varchar2_table(102) := 'container>'||wwv_flow.LF||
'													<fo:block line-height="inherit" margin-bottom="0.00in" margin-left="0.00in" ';
wwv_flow_imp.g_varchar2_table(103) := 'margin-right="0.00in + 100% - 100%" margin-top="0.00in" margin="0pt">'||wwv_flow.LF||
'														<fo:inline font-';
wwv_flow_imp.g_varchar2_table(104) := 'size="14.67px">'||wwv_flow.LF||
'															<xsl:text>305, Mahindra Chambers, 619/28, W.T. Patil Marg, Chembur (E';
wwv_flow_imp.g_varchar2_table(105) := 'ast), Mumbai-400 071. INDIA </xsl:text>'||wwv_flow.LF||
'														</fo:inline>'||wwv_flow.LF||
'														<fo:block/>'||wwv_flow.LF||
'							';
wwv_flow_imp.g_varchar2_table(106) := '							<fo:inline font-size="14.67px">'||wwv_flow.LF||
'															<xsl:text>Tel. (022) 25205488 / Fax (022) 2521';
wwv_flow_imp.g_varchar2_table(107) := '5488/ e: januz@januzuniversal.in</xsl:text>'||wwv_flow.LF||
'														</fo:inline>'||wwv_flow.LF||
'													</fo:block>'||wwv_flow.LF||
'				';
wwv_flow_imp.g_varchar2_table(108) := '								</fo:block>'||wwv_flow.LF||
'											</fo:table-cell>'||wwv_flow.LF||
'											<fo:table-cell font-size="10pt" padding="';
wwv_flow_imp.g_varchar2_table(109) := '0" display-align="center">'||wwv_flow.LF||
'												<fo:block text-align="right">'||wwv_flow.LF||
'													<fo:inline font-we';
wwv_flow_imp.g_varchar2_table(110) := 'ight="bold">'||wwv_flow.LF||
'														<xsl:text>Page: </xsl:text>'||wwv_flow.LF||
'													</fo:inline>'||wwv_flow.LF||
'													<fo:pa';
wwv_flow_imp.g_varchar2_table(111) := 'ge-number font-weight="bold"/>'||wwv_flow.LF||
'												</fo:block>'||wwv_flow.LF||
'											</fo:table-cell>'||wwv_flow.LF||
'										</fo:ta';
wwv_flow_imp.g_varchar2_table(112) := 'ble-row>'||wwv_flow.LF||
'									</xsl:variable>'||wwv_flow.LF||
'									<xsl:choose>'||wwv_flow.LF||
'										<xsl:when test="string($altova:tab';
wwv_flow_imp.g_varchar2_table(113) := 'lerows)">'||wwv_flow.LF||
'											<xsl:copy-of select="$altova:tablerows"/>'||wwv_flow.LF||
'										</xsl:when>'||wwv_flow.LF||
'										<xsl:';
wwv_flow_imp.g_varchar2_table(114) := 'otherwise>'||wwv_flow.LF||
'											<fo:table-row>'||wwv_flow.LF||
'												<fo:table-cell>'||wwv_flow.LF||
'													<fo:block/>'||wwv_flow.LF||
'										';
wwv_flow_imp.g_varchar2_table(115) := '		</fo:table-cell>'||wwv_flow.LF||
'											</fo:table-row>'||wwv_flow.LF||
'										</xsl:otherwise>'||wwv_flow.LF||
'									</xsl:choose>'||wwv_flow.LF||
'				';
wwv_flow_imp.g_varchar2_table(116) := '				</fo:table-body>'||wwv_flow.LF||
'							</fo:table>'||wwv_flow.LF||
'						</fo:block>'||wwv_flow.LF||
'					</fo:block-container>'||wwv_flow.LF||
'				</fo:static';
wwv_flow_imp.g_varchar2_table(117) := '-content>'||wwv_flow.LF||
'				<fo:static-content flow-name="even-page-footer">'||wwv_flow.LF||
'					<fo:block-container height="0.51';
wwv_flow_imp.g_varchar2_table(118) := 'in" overflow="hidden" display-align="after">'||wwv_flow.LF||
'						<fo:block>'||wwv_flow.LF||
'							<fo:inline-container>'||wwv_flow.LF||
'								<';
wwv_flow_imp.g_varchar2_table(119) := 'fo:block>'||wwv_flow.LF||
'									<xsl:text>&#x200B;</xsl:text>'||wwv_flow.LF||
'								</fo:block>'||wwv_flow.LF||
'							</fo:inline-container>'||wwv_flow.LF||
'	';
wwv_flow_imp.g_varchar2_table(120) := '						<fo:table width="100%" table-layout="fixed" border-spacing="2pt">'||wwv_flow.LF||
'								<fo:table-column col';
wwv_flow_imp.g_varchar2_table(121) := 'umn-width="90%"/>'||wwv_flow.LF||
'								<fo:table-column column-width="10%"/>'||wwv_flow.LF||
'								<xsl:variable name="altova:C';
wwv_flow_imp.g_varchar2_table(122) := 'urrContextGrid_2" select="."/>'||wwv_flow.LF||
'								<fo:table-body start-indent="0pt">'||wwv_flow.LF||
'									<xsl:variable nam';
wwv_flow_imp.g_varchar2_table(123) := 'e="altova:tablerows">'||wwv_flow.LF||
'										<fo:table-row>'||wwv_flow.LF||
'											<fo:table-cell number-columns-spanned="2" ';
wwv_flow_imp.g_varchar2_table(124) := 'padding="0" display-align="center">'||wwv_flow.LF||
'												<fo:block text-align="left">'||wwv_flow.LF||
'													<fo:block ';
wwv_flow_imp.g_varchar2_table(125) := 'text-align="center">'||wwv_flow.LF||
'														<fo:leader leader-pattern="rule" rule-thickness="1" leader-length';
wwv_flow_imp.g_varchar2_table(126) := '="100%" color="black"/>'||wwv_flow.LF||
'													</fo:block>'||wwv_flow.LF||
'												</fo:block>'||wwv_flow.LF||
'											</fo:table-cell>';
wwv_flow_imp.g_varchar2_table(127) := ''||wwv_flow.LF||
'										</fo:table-row>'||wwv_flow.LF||
'										<fo:table-row>'||wwv_flow.LF||
'											<fo:table-cell font-size="10pt" paddi';
wwv_flow_imp.g_varchar2_table(128) := 'ng="0" display-align="center">'||wwv_flow.LF||
'												<fo:block text-align="center">'||wwv_flow.LF||
'													<fo:block>'||wwv_flow.LF||
'		';
wwv_flow_imp.g_varchar2_table(129) := '												<fo:leader leader-pattern="space"/>'||wwv_flow.LF||
'													</fo:block>'||wwv_flow.LF||
'													<fo:inline-con';
wwv_flow_imp.g_varchar2_table(130) := 'tainer>'||wwv_flow.LF||
'														<fo:block>'||wwv_flow.LF||
'															<xsl:text>&#x200B;</xsl:text>'||wwv_flow.LF||
'														</fo:blo';
wwv_flow_imp.g_varchar2_table(131) := 'ck>'||wwv_flow.LF||
'													</fo:inline-container>'||wwv_flow.LF||
'													<fo:block line-height="inherit" margin-bottom="';
wwv_flow_imp.g_varchar2_table(132) := '0.00in" margin-left="0.00in" margin-right="0.00in + 100% - 100%" margin-top="0.00in" margin="0pt">'||wwv_flow.LF||
'	';
wwv_flow_imp.g_varchar2_table(133) := '													<fo:inline font-size="14.67px">'||wwv_flow.LF||
'															<xsl:text>305, Mahindra Chambers, 619/28';
wwv_flow_imp.g_varchar2_table(134) := ', W.T. Patil Marg, Chembur (East), Mumbai-400 071. INDIA </xsl:text>'||wwv_flow.LF||
'														</fo:inline>'||wwv_flow.LF||
'				';
wwv_flow_imp.g_varchar2_table(135) := '										<fo:block/>'||wwv_flow.LF||
'														<fo:inline font-size="14.67px">'||wwv_flow.LF||
'															<xsl:text>Tel. (0';
wwv_flow_imp.g_varchar2_table(136) := '22) 25205488 / Fax (022) 25215488/ e: januz@januzuniversal.in</xsl:text>'||wwv_flow.LF||
'														</fo:inline>'||wwv_flow.LF||
'';
wwv_flow_imp.g_varchar2_table(137) := '													</fo:block>'||wwv_flow.LF||
'												</fo:block>'||wwv_flow.LF||
'											</fo:table-cell>'||wwv_flow.LF||
'											<fo:table-ce';
wwv_flow_imp.g_varchar2_table(138) := 'll font-size="10pt" padding="0" display-align="center">'||wwv_flow.LF||
'												<fo:block text-align="right">'||wwv_flow.LF||
'		';
wwv_flow_imp.g_varchar2_table(139) := '											<fo:inline font-weight="bold">'||wwv_flow.LF||
'														<xsl:text>Page: </xsl:text>'||wwv_flow.LF||
'													</f';
wwv_flow_imp.g_varchar2_table(140) := 'o:inline>'||wwv_flow.LF||
'													<fo:page-number font-weight="bold"/>'||wwv_flow.LF||
'												</fo:block>'||wwv_flow.LF||
'											</fo:';
wwv_flow_imp.g_varchar2_table(141) := 'table-cell>'||wwv_flow.LF||
'										</fo:table-row>'||wwv_flow.LF||
'									</xsl:variable>'||wwv_flow.LF||
'									<xsl:choose>'||wwv_flow.LF||
'										<xsl:';
wwv_flow_imp.g_varchar2_table(142) := 'when test="string($altova:tablerows)">'||wwv_flow.LF||
'											<xsl:copy-of select="$altova:tablerows"/>'||wwv_flow.LF||
'								';
wwv_flow_imp.g_varchar2_table(143) := '		</xsl:when>'||wwv_flow.LF||
'										<xsl:otherwise>'||wwv_flow.LF||
'											<fo:table-row>'||wwv_flow.LF||
'												<fo:table-cell>'||wwv_flow.LF||
'						';
wwv_flow_imp.g_varchar2_table(144) := '							<fo:block/>'||wwv_flow.LF||
'												</fo:table-cell>'||wwv_flow.LF||
'											</fo:table-row>'||wwv_flow.LF||
'										</xsl:otherwise';
wwv_flow_imp.g_varchar2_table(145) := '>'||wwv_flow.LF||
'									</xsl:choose>'||wwv_flow.LF||
'								</fo:table-body>'||wwv_flow.LF||
'							</fo:table>'||wwv_flow.LF||
'						</fo:block>'||wwv_flow.LF||
'					</fo:blo';
wwv_flow_imp.g_varchar2_table(146) := 'ck-container>'||wwv_flow.LF||
'				</fo:static-content>'||wwv_flow.LF||
'				<fo:flow flow-name="xsl-region-body">'||wwv_flow.LF||
'					<fo:block>'||wwv_flow.LF||
'			';
wwv_flow_imp.g_varchar2_table(147) := '			<fo:block>'||wwv_flow.LF||
'							<fo:leader leader-pattern="space"/>'||wwv_flow.LF||
'						</fo:block>'||wwv_flow.LF||
'						<fo:inline-containe';
wwv_flow_imp.g_varchar2_table(148) := 'r>'||wwv_flow.LF||
'							<fo:block>'||wwv_flow.LF||
'								<xsl:text>&#x200B;</xsl:text>'||wwv_flow.LF||
'							</fo:block>'||wwv_flow.LF||
'						</fo:inline-cont';
wwv_flow_imp.g_varchar2_table(149) := 'ainer>'||wwv_flow.LF||
'						<fo:block line-height="16.87px" margin-bottom="13.33px" margin-left="0.00in" margin-rig';
wwv_flow_imp.g_varchar2_table(150) := 'ht="0.00in + 100% - 100%" margin-top="0.00in" text-align="center" margin="0pt">'||wwv_flow.LF||
'							<fo:inline fo';
wwv_flow_imp.g_varchar2_table(151) := 'nt-size="14.67px">'||wwv_flow.LF||
'								<xsl:text>PROFORMA INVOICE</xsl:text>'||wwv_flow.LF||
'							</fo:inline>'||wwv_flow.LF||
'						</fo:bloc';
wwv_flow_imp.g_varchar2_table(152) := 'k>'||wwv_flow.LF||
'						<fo:block>'||wwv_flow.LF||
'							<fo:leader leader-pattern="space"/>'||wwv_flow.LF||
'						</fo:block>'||wwv_flow.LF||
'						<fo:block>'||wwv_flow.LF||
'		';
wwv_flow_imp.g_varchar2_table(153) := '					<fo:leader leader-pattern="space"/>'||wwv_flow.LF||
'						</fo:block>'||wwv_flow.LF||
'					</fo:block>'||wwv_flow.LF||
'					<fo:block id="SV_Re';
wwv_flow_imp.g_varchar2_table(154) := 'fID_PageTotal"/>'||wwv_flow.LF||
'				</fo:flow>'||wwv_flow.LF||
'			</fo:page-sequence>'||wwv_flow.LF||
'		</fo:root>'||wwv_flow.LF||
'	</xsl:template>'||wwv_flow.LF||
'	<xsl:template ';
wwv_flow_imp.g_varchar2_table(155) := 'name="altova:double-backslash">'||wwv_flow.LF||
'		<xsl:param name="text"/>'||wwv_flow.LF||
'		<xsl:param name="text-length"/>'||wwv_flow.LF||
'		<xsl:';
wwv_flow_imp.g_varchar2_table(156) := 'variable name="text-after-bs" select="substring-after($text, ''\'')"/>'||wwv_flow.LF||
'		<xsl:variable name="text-afte';
wwv_flow_imp.g_varchar2_table(157) := 'r-bs-length" select="string-length($text-after-bs)"/>'||wwv_flow.LF||
'		<xsl:choose>'||wwv_flow.LF||
'			<xsl:when test="$text-after-';
wwv_flow_imp.g_varchar2_table(158) := 'bs-length = 0">'||wwv_flow.LF||
'				<xsl:choose>'||wwv_flow.LF||
'					<xsl:when test="substring($text, $text-length) = ''\''">'||wwv_flow.LF||
'						<';
wwv_flow_imp.g_varchar2_table(159) := 'xsl:value-of select="concat(substring($text,1,$text-length - 1), ''\\'')"/>'||wwv_flow.LF||
'					</xsl:when>'||wwv_flow.LF||
'					<xsl';
wwv_flow_imp.g_varchar2_table(160) := ':otherwise>'||wwv_flow.LF||
'						<xsl:value-of select="$text"/>'||wwv_flow.LF||
'					</xsl:otherwise>'||wwv_flow.LF||
'				</xsl:choose>'||wwv_flow.LF||
'			</xsl:wh';
wwv_flow_imp.g_varchar2_table(161) := 'en>'||wwv_flow.LF||
'			<xsl:otherwise>'||wwv_flow.LF||
'				<xsl:value-of select="concat(substring($text,1,$text-length - $text-after';
wwv_flow_imp.g_varchar2_table(162) := '-bs-length - 1), ''\\'')"/>'||wwv_flow.LF||
'				<xsl:call-template name="altova:double-backslash">'||wwv_flow.LF||
'					<xsl:with-para';
wwv_flow_imp.g_varchar2_table(163) := 'm name="text" select="$text-after-bs"/>'||wwv_flow.LF||
'					<xsl:with-param name="text-length" select="$text-after-';
wwv_flow_imp.g_varchar2_table(164) := 'bs-length"/>'||wwv_flow.LF||
'				</xsl:call-template>'||wwv_flow.LF||
'			</xsl:otherwise>'||wwv_flow.LF||
'		</xsl:choose>'||wwv_flow.LF||
'	</xsl:template>'||wwv_flow.LF||
'	<xsl:tem';
wwv_flow_imp.g_varchar2_table(165) := 'plate name="altova:MakeValueAbsoluteIfPixels">'||wwv_flow.LF||
'		<xsl:param name="sValue"/>'||wwv_flow.LF||
'		<xsl:variable name="sB';
wwv_flow_imp.g_varchar2_table(166) := 'eforePx" select="substring-before($sValue, ''px'')"/>'||wwv_flow.LF||
'		<xsl:choose>'||wwv_flow.LF||
'			<xsl:when test="$sBeforePx">'||wwv_flow.LF||
'	';
wwv_flow_imp.g_varchar2_table(167) := '			<xsl:variable name="nLengthOfInteger">'||wwv_flow.LF||
'					<xsl:call-template name="altova:GetCharCountOfInteger';
wwv_flow_imp.g_varchar2_table(168) := 'AtEndOfString">'||wwv_flow.LF||
'						<xsl:with-param name="sText" select="$sBeforePx"/>'||wwv_flow.LF||
'					</xsl:call-template>'||wwv_flow.LF||
'	';
wwv_flow_imp.g_varchar2_table(169) := '			</xsl:variable>'||wwv_flow.LF||
'				<xsl:variable name="nPosOfInteger" select="string-length($sBeforePx) - $nLeng';
wwv_flow_imp.g_varchar2_table(170) := 'thOfInteger + 1"/>'||wwv_flow.LF||
'				<xsl:variable name="nValuePx" select="substring($sBeforePx, $nPosOfInteger)"/';
wwv_flow_imp.g_varchar2_table(171) := '>'||wwv_flow.LF||
'				<xsl:variable name="nValueIn" select="number($nValuePx) div number($altova:nPxPerIn)"/>'||wwv_flow.LF||
'				<x';
wwv_flow_imp.g_varchar2_table(172) := 'sl:variable name="nLengthBeforeInteger" select="string-length($sBeforePx) - $nLengthOfInteger"/>'||wwv_flow.LF||
'			';
wwv_flow_imp.g_varchar2_table(173) := '	<xsl:variable name="sRest">'||wwv_flow.LF||
'					<xsl:call-template name="altova:MakeValueAbsoluteIfPixels">'||wwv_flow.LF||
'						';
wwv_flow_imp.g_varchar2_table(174) := '<xsl:with-param name="sValue" select="substring-after($sValue, ''px'')"/>'||wwv_flow.LF||
'					</xsl:call-template>'||wwv_flow.LF||
'		';
wwv_flow_imp.g_varchar2_table(175) := '		</xsl:variable>'||wwv_flow.LF||
'				<xsl:value-of select="concat(substring($sBeforePx, 1, $nLengthBeforeInteger), ';
wwv_flow_imp.g_varchar2_table(176) := 'string($nValueIn), ''in'', $sRest)"/>'||wwv_flow.LF||
'			</xsl:when>'||wwv_flow.LF||
'			<xsl:otherwise>'||wwv_flow.LF||
'				<xsl:value-of select="$sVa';
wwv_flow_imp.g_varchar2_table(177) := 'lue"/>'||wwv_flow.LF||
'			</xsl:otherwise>'||wwv_flow.LF||
'		</xsl:choose>'||wwv_flow.LF||
'	</xsl:template>'||wwv_flow.LF||
'	<xsl:template name="altova:GetCharCount';
wwv_flow_imp.g_varchar2_table(178) := 'OfIntegerAtEndOfString">'||wwv_flow.LF||
'		<xsl:param name="sText"/>'||wwv_flow.LF||
'		<xsl:variable name="sLen" select="string-leng';
wwv_flow_imp.g_varchar2_table(179) := 'th($sText)"/>'||wwv_flow.LF||
'		<xsl:variable name="cLast" select="substring($sText, $sLen)"/>'||wwv_flow.LF||
'		<xsl:choose>'||wwv_flow.LF||
'			<xs';
wwv_flow_imp.g_varchar2_table(180) := 'l:when test="number($cLast) &gt;= 0 and number($cLast) &lt;= 9">'||wwv_flow.LF||
'				<xsl:variable name="nResultOfRe';
wwv_flow_imp.g_varchar2_table(181) := 'st">'||wwv_flow.LF||
'					<xsl:call-template name="altova:GetCharCountOfIntegerAtEndOfString">'||wwv_flow.LF||
'						<xsl:with-param';
wwv_flow_imp.g_varchar2_table(182) := ' name="sText" select="substring($sText, 1, $sLen - 1)"/>'||wwv_flow.LF||
'					</xsl:call-template>'||wwv_flow.LF||
'				</xsl:variabl';
wwv_flow_imp.g_varchar2_table(183) := 'e>'||wwv_flow.LF||
'				<xsl:value-of select="$nResultOfRest + 1"/>'||wwv_flow.LF||
'			</xsl:when>'||wwv_flow.LF||
'			<xsl:otherwise>'||wwv_flow.LF||
'				<xsl:text>0';
wwv_flow_imp.g_varchar2_table(184) := '</xsl:text>'||wwv_flow.LF||
'			</xsl:otherwise>'||wwv_flow.LF||
'		</xsl:choose>'||wwv_flow.LF||
'	</xsl:template>'||wwv_flow.LF||
'</xsl:stylesheet>'||wwv_flow.LF||
'';
wwv_flow_imp.component_end;
end;
/
begin
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.15'
,p_default_workspace_id=>7965342552622829
,p_default_application_id=>200
,p_default_id_offset=>32162224829641601
,p_default_owner=>'SAARTHIDEV'
);
wwv_flow_imp_shared.create_report_layout(
 p_id=>wwv_flow_imp.id(163714311198666693)
,p_report_layout_name=>'test'
,p_static_id=>'TEST_243765154585302419'
,p_report_layout_type=>'XSL_FILE'
,p_varchar2_table=>wwv_flow_imp.g_varchar2_table
,p_version_scn=>350683253
);
wwv_flow_imp.component_end;
end;
/
