prompt --application/pages/page_00025
begin
--   Manifest
--     PAGE: 00025
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.15'
,p_default_workspace_id=>7965342552622829
,p_default_application_id=>200
,p_default_id_offset=>32162224829641601
,p_default_owner=>'SAARTHIDEV'
);
wwv_flow_imp_page.create_page(
 p_id=>25
,p_name=>'HSN Code Report'
,p_alias=>'HSN-CODE-REPORT'
,p_step_title=>'HSN Code Report'
,p_autocomplete_on_off=>'OFF'
,p_page_template_options=>'#DEFAULT#'
,p_page_component_map=>'18'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(172508770309030886)
,p_plug_name=>'HSN Code'
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>2100526641005906379
,p_plug_display_sequence=>10
,p_query_type=>'SQL'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'select HCM_ID, ',
'HCM_CODE,',
'HCM_DESCRIPTION,',
'HCM_CHAPTER,',
'HCM_END_USE_CODE,',
'HCM_CREATED_BY,',
'HCM_CREATED_ON,',
'HCM_UPDATED_BY,',
'HCM_UPDATED_ON,',
'HCM_APEDA_FLAG,',
'HCM_APEDA_COUNTRY,',
'HCM_SPICES_FLAG,',
'HCM_SPICES_COUNTRY,',
'HCM_TEA_FLAG,',
'HCM_TEA_COUNTRY,',
'HCM_TOBACCO_FLAG,',
'HCM_TOBACCO_COUNTRY,',
'HCM_DRAWBACK,',
'--HCM_MEIS, Commented by Rahul on 02-Feb-24 as MEIS scheme is discontinued',
'to_char(HCM_RoDTEP,''0.00'') || nvl2(HCM_RoDTEP,''%'','''') || nvl2(HCM_CAP,'' - '','''') || HCM_CAP RoDTEP',
',HCM_CESS_FLAG --Added by Rahul on 02-Feb-24 to consider this flag in custom invoice cess calculation',
',HCM_FSSAI_FLAG',
'from V_HSN_CODE_MASTER'))
,p_plug_source_type=>'NATIVE_IR'
);
wwv_flow_imp_page.create_worksheet(
 p_id=>wwv_flow_imp.id(172509152950030889)
,p_name=>'Report 1'
,p_max_row_count=>'1000000'
,p_max_row_count_message=>'The maximum row count for this report is #MAX_ROW_COUNT# rows.  Please apply a filter to reduce the number of records in your query.'
,p_no_data_found_message=>'No data found.'
,p_allow_save_rpt_public=>'Y'
,p_show_nulls_as=>'-'
,p_pagination_type=>'ROWS_X_TO_Y'
,p_pagination_display_pos=>'BOTTOM_RIGHT'
,p_show_display_row_count=>'Y'
,p_report_list_mode=>'TABS'
,p_lazy_loading=>false
,p_show_detail_link=>'C'
,p_show_rows_per_page=>'N'
,p_show_notify=>'Y'
,p_download_formats=>'CSV:HTML:XLSX:PDF'
,p_enable_mail_download=>'Y'
,p_detail_link=>'f?p=&APP_ID.:26:&APP_SESSION.::::P26_HCM_ID:#HCM_ID#'
,p_detail_link_text=>'<img src="#IMAGE_PREFIX#app_ui/img/icons/apex-edit-pencil-alt.png" class="apex-edit-pencil-alt" alt="">'
,p_owner=>'RANU'
,p_internal_uid=>13840374807187200399
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(12702449824041344500)
,p_db_column_name=>'HCM_ID'
,p_display_order=>1
,p_column_identifier=>'A'
,p_column_label=>'ID'
,p_column_type=>'NUMBER'
,p_display_text_as=>'HIDDEN'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(12702449382495344500)
,p_db_column_name=>'HCM_CODE'
,p_display_order=>2
,p_column_identifier=>'B'
,p_column_label=>'Code'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(12702448986805344500)
,p_db_column_name=>'HCM_DESCRIPTION'
,p_display_order=>3
,p_column_identifier=>'C'
,p_column_label=>'Description'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(12702448643864344500)
,p_db_column_name=>'HCM_CHAPTER'
,p_display_order=>4
,p_column_identifier=>'D'
,p_column_label=>'Chapter'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(12702448249087344500)
,p_db_column_name=>'HCM_END_USE_CODE'
,p_display_order=>5
,p_column_identifier=>'E'
,p_column_label=>'End Use Code'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(12702447834501344500)
,p_db_column_name=>'HCM_CREATED_BY'
,p_display_order=>6
,p_column_identifier=>'F'
,p_column_label=>'Created By'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(12702447407393344500)
,p_db_column_name=>'HCM_CREATED_ON'
,p_display_order=>7
,p_column_identifier=>'G'
,p_column_label=>'Created On'
,p_column_type=>'DATE'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(12702447022427344499)
,p_db_column_name=>'HCM_UPDATED_BY'
,p_display_order=>8
,p_column_identifier=>'H'
,p_column_label=>'Updated By'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(12702446648899344499)
,p_db_column_name=>'HCM_UPDATED_ON'
,p_display_order=>9
,p_column_identifier=>'I'
,p_column_label=>'Updated On'
,p_column_type=>'DATE'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(12702446182991344499)
,p_db_column_name=>'HCM_APEDA_FLAG'
,p_display_order=>10
,p_column_identifier=>'J'
,p_column_label=>'Apeda Return ?'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(12702445836981344499)
,p_db_column_name=>'HCM_APEDA_COUNTRY'
,p_display_order=>11
,p_column_identifier=>'K'
,p_column_label=>'Apeda Country'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(12702445449556344499)
,p_db_column_name=>'HCM_SPICES_FLAG'
,p_display_order=>12
,p_column_identifier=>'L'
,p_column_label=>'Spices Return ?'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(12702445003682344499)
,p_db_column_name=>'HCM_SPICES_COUNTRY'
,p_display_order=>13
,p_column_identifier=>'M'
,p_column_label=>'Spices Country'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(12702444662234344499)
,p_db_column_name=>'HCM_TEA_FLAG'
,p_display_order=>14
,p_column_identifier=>'N'
,p_column_label=>'Tea Return ?'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(12702444199503344498)
,p_db_column_name=>'HCM_TEA_COUNTRY'
,p_display_order=>15
,p_column_identifier=>'O'
,p_column_label=>'Tea Country'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(12702443795690344498)
,p_db_column_name=>'HCM_TOBACCO_FLAG'
,p_display_order=>16
,p_column_identifier=>'P'
,p_column_label=>'Tobacco Return ?'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(12702443401622344498)
,p_db_column_name=>'HCM_TOBACCO_COUNTRY'
,p_display_order=>17
,p_column_identifier=>'Q'
,p_column_label=>'Tobacco Country'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(12702450608664344501)
,p_db_column_name=>'HCM_DRAWBACK'
,p_display_order=>27
,p_column_identifier=>'R'
,p_column_label=>'Drawback'
,p_column_type=>'STRING'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(12702451077143344504)
,p_db_column_name=>'RODTEP'
,p_display_order=>47
,p_column_identifier=>'T'
,p_column_label=>'RoDTEP'
,p_column_type=>'STRING'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(22047782595929672129)
,p_db_column_name=>'HCM_CESS_FLAG'
,p_display_order=>57
,p_column_identifier=>'U'
,p_column_label=>'CESS'
,p_column_type=>'STRING'
,p_column_alignment=>'CENTER'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(29171428818948498026)
,p_db_column_name=>'HCM_FSSAI_FLAG'
,p_display_order=>67
,p_column_identifier=>'V'
,p_column_label=>'FSSAI Return ?'
,p_column_type=>'STRING'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_rpt(
 p_id=>wwv_flow_imp.id(172518479705033136)
,p_application_user=>'APXWS_DEFAULT'
,p_report_seq=>10
,p_report_alias=>'9875410'
,p_status=>'PUBLIC'
,p_is_default=>'Y'
,p_report_columns=>'HCM_CODE:HCM_CHAPTER:HCM_DESCRIPTION:HCM_END_USE_CODE:HCM_UPDATED_BY:HCM_UPDATED_ON:HCM_APEDA_FLAG:HCM_SPICES_FLAG:HCM_SPICES_COUNTRY:HCM_TEA_FLAG:HCM_TOBACCO_FLAG:HCM_FSSAI_FLAG:HCM_CESS_FLAG:HCM_DRAWBACK:RODTEP:'
,p_sort_column_1=>'HCM_UPDATED_ON'
,p_sort_direction_1=>'DESC'
);
wwv_flow_imp_page.create_page_button(
 p_id=>wwv_flow_imp.id(12702442584749344494)
,p_button_sequence=>30
,p_button_plug_id=>wwv_flow_imp.id(172508770309030886)
,p_button_name=>'CREATE'
,p_button_action=>'REDIRECT_PAGE'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>4072362960822175091
,p_button_is_hot=>'Y'
,p_button_image_alt=>'Create'
,p_button_position=>'RIGHT_OF_IR_SEARCH_BAR'
,p_button_alignment=>'RIGHT'
,p_button_redirect_url=>'f?p=&APP_ID.:26:&SESSION.::&DEBUG.:26'
);
wwv_flow_imp_page.create_page_da_event(
 p_id=>wwv_flow_imp.id(12702442265470344481)
,p_name=>'Edit Report - Dialog Closed'
,p_event_sequence=>10
,p_triggering_element_type=>'REGION'
,p_triggering_region_id=>wwv_flow_imp.id(172508770309030886)
,p_bind_type=>'bind'
,p_execution_type=>'IMMEDIATE'
,p_bind_event_type=>'apexafterclosedialog'
);
wwv_flow_imp_page.create_page_da_action(
 p_id=>wwv_flow_imp.id(12702441815329344479)
,p_event_id=>wwv_flow_imp.id(12702442265470344481)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_REFRESH'
,p_affected_elements_type=>'REGION'
,p_affected_region_id=>wwv_flow_imp.id(172508770309030886)
,p_attribute_01=>'N'
);
wwv_flow_imp_page.create_page_da_event(
 p_id=>wwv_flow_imp.id(12702441413575344479)
,p_name=>'Create Button - Dialog Closed'
,p_event_sequence=>20
,p_triggering_element_type=>'BUTTON'
,p_triggering_button_id=>wwv_flow_imp.id(12702442584749344494)
,p_bind_type=>'bind'
,p_execution_type=>'IMMEDIATE'
,p_bind_event_type=>'apexafterclosedialog'
);
wwv_flow_imp_page.create_page_da_action(
 p_id=>wwv_flow_imp.id(12702440896390344479)
,p_event_id=>wwv_flow_imp.id(12702441413575344479)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_REFRESH'
,p_affected_elements_type=>'REGION'
,p_affected_region_id=>wwv_flow_imp.id(172508770309030886)
,p_attribute_01=>'N'
);
wwv_flow_imp.component_end;
end;
/
